/**
 * GET /api/geo/search?q=varthur          — typeahead for a place
 * GET /api/geo/search?place_id=ChIJ…     — resolve a chosen prediction
 *
 * THE BUG THIS FIXES
 *   Searching "Varthur" returned nothing. The India Post directory spells that post
 *   office "Vartur S.O" — no 'h' — and the previous implementation was a literal
 *   substring match over our own catalogue, so the spelling students actually use
 *   could never match. Fuzzy-matching our way out would have been guesswork against
 *   one department's transliteration choices for 155,000 offices.
 *
 *   A geocoder already knows both spellings, every colloquial name and the current
 *   district boundaries. That is the whole reason for the switch (#101 follow-up).
 *
 * TWO CALLS, BECAUSE AUTOCOMPLETE RETURNS NAMES NOT ADDRESSES
 *   Autocomplete gives predictions + place_ids; the address components come from a
 *   Details lookup on the chosen one. So the client searches, the student picks, and
 *   only THEN do we spend a Details call — one per completed search rather than one
 *   per keystroke.
 *
 * NO LOCAL FALLBACK. A substring match over India Post's spellings is precisely what
 * failed — and it cannot be fixed by fuzzy matching one department's transliteration of
 * 155,000 names. If search is unavailable the student uses the PIN box instead.
 */
import { NextResponse, type NextRequest } from "next/server";
import { createClient } from "@/lib/supabase/server";
import {
  providerAutocomplete,
  providerDetails,
  providerConfigured,
  sweepProviderCache,
} from "@/lib/geo-provider";

export async function GET(req: NextRequest) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: "Not authenticated" }, { status: 401 });

  const sp = req.nextUrl.searchParams;
  const placeId = (sp.get("place_id") ?? "").trim();
  const q = (sp.get("q") ?? "").trim();
  // The session token bundles one search's keystrokes into a single billable
  // Autocomplete session instead of billing each request. Generated by the client
  // and passed straight through — it is an opaque grouping key, not a credential.
  const sessionToken = (sp.get("session") ?? "").trim() || undefined;

  sweepProviderCache(supabase);

  // ── stage 2: a prediction was chosen → its address fields ───────────────
  if (placeId) {
    const record = await providerDetails(supabase, placeId);
    if (!record) {
      return NextResponse.json(
        { error: "Couldn't load that place. Please enter your PIN code." },
        { status: 404 },
      );
    }
    return NextResponse.json({ result: record, source: "provider" });
  }

  // 2 chars minimum: a single letter matches everything and tells us nothing.
  if (q.length < 2) return NextResponse.json({ results: [] });

  // ── stage 1: predictions ────────────────────────────────────────────────
  if (providerConfigured()) {
    const preds = await providerAutocomplete(supabase, q, sessionToken);
    if (preds) {
      return NextResponse.json({
        source: "provider",
        // `needsDetails` tells the client these carry no address yet — picking one
        // costs a second round trip. Without the flag the UI would have to infer it
        // from the shape of the payload.
        needsDetails: true,
        results: preds,
      });
    }
  }

  // No catalogue fallback (#101 follow-up): a substring match over India Post's
  // spellings is what made "Varthur" return nothing at all — the office is recorded as
  // "Vartur S.O". Better to say we can't search than to answer wrongly.
  return NextResponse.json(
    {
      results: [],
      error: providerConfigured() ? "unavailable" : "not_configured",
      message: providerConfigured()
        ? "Search is unavailable right now. Please enter your PIN code."
        : "Place search isn't configured. Please enter your PIN code.",
    },
    { status: providerConfigured() ? 503 : 404 },
  );
}
