-- ============================================================================
-- 008_college_seed_11.sql  —  part 11 of 11
-- College seed (continued). Idempotent via ON CONFLICT. See part 01 for notes.
-- ============================================================================

insert into public.college (name, place, address, district, state, pincode, ownership_type) values
    ('Sri Krishna College', 'Bagula', 'Bagula, District Nadia - 741 502, West Bengal', 'Nadia', 'West Bengal', '741502', 'PRIVATE'),
    ('Sripat Singh College', 'Jiaganj', 'Jiaganj, District Murshidabad - 742 123, West Bengal', 'Murshidabad', 'West Bengal', '742123', 'PRIVATE'),
    ('Subhas Chandra Bose Covtenary College', 'Lalbagh', 'Lalbagh, Murshidabad, West Bengal', null, 'West Bengal', null, 'PRIVATE'),
    ('Sudhiranjan Lahari Mahavidyalaya', 'Majdia', 'Majdia - 741 507, District Nadia, West Bengal', 'Nadia', 'West Bengal', '741507', 'PRIVATE'),
    ('Union christian Training College', 'Berhampore', 'Berhampore, District Murshidabad - 742 101, West Bengal', 'Murshidabad', 'West Bengal', '742101', 'PRIVATE'),
    ('Acharya B.N. Seal College', 'Cooch Behar', 'Cooch Behar, District Cooch Behar, West Bengal', 'Cooch Behar', 'West Bengal', null, 'GOVERNMENT'),
    ('Acharya Prafulla Chandra Roy Government College', 'Matigara, Siliguri', 'Himachal Vihar, Matigara, Siliguri - 734 010, Dist. Darjeeling, West Bengal', 'Darjeeling', 'West Bengal', '734010', 'GOVERNMENT'),
    ('Alipurduar College', 'Alipurdia Court', 'P.O. Alipurdia Court, District Jalpaiguri, West Bengal', 'Jalpaiguri', 'West Bengal', null, 'PRIVATE'),
    ('Anand Chandra College', 'Jalpaiguri', 'Jalpaiguri, District Jalpaiguri - 735 101, West Bengal', 'Jalpaiguri', 'West Bengal', '735101', 'PRIVATE'),
    ('Anand Chandra College of Commerce', 'Jalpaiguri', 'Jalpaiguri, District Jalpaiguri - 735 101, West Bengal', 'Jalpaiguri', 'West Bengal', '735101', 'PRIVATE'),
    ('Ananda Chandra Training College', 'Jalpaiguri', 'Jalpaiguri, District Jalpaiguri - 735 101, West Bengal', 'Jalpaiguri', 'West Bengal', '735101', 'PRIVATE'),
    ('Balurghat College', 'Balurghat', 'Balurghat, District South Dinajpur - 733 101, West Bengal', 'South Dinajpur', 'West Bengal', '733101', 'PRIVATE'),
    ('Balurghat Mahila Mahavidyalaya', 'Balurghat', 'Balurghat, District Dakshin Dinajpur - 733 101, West Bengal', 'Dakshin Dinajpur', 'West Bengal', '733101', 'PRIVATE'),
    ('Birapara College', 'Jalpaiguri', 'Jalpaiguri, District Jalpaiguri - 735 204, West Bengal', 'Jalpaiguri', 'West Bengal', '735204', 'PRIVATE'),
    ('Chanchal College', 'Chanchal', 'Chanchal, District Malda - 732 123, West Bengal', 'Malda', 'West Bengal', '732123', 'PRIVATE'),
    ('Cluny Women’s College', 'Kalimpong', '8th Mile, Kalimpong-734 301, District Darjeeling, West Bengal', 'Darjeeling', 'West Bengal', '734301', 'PRIVATE'),
    ('Cooach Behar College', 'Kalighat Road', 'Kalighat Road, District Cooch Behar - 736 101, West Bengal', 'Cooch Behar', 'West Bengal', '736101', 'PRIVATE'),
    ('Darjeeling Governement College', 'North Point Darjeeling', 'P.O. North Point Darjeeling, District Darjeeling - 734 101, West Bengal', 'Darjeeling', 'West Bengal', '734101', 'GOVERNMENT'),
    ('Dewan Abdul Gani College', 'Harirampur', 'Harirampur, South Dinajpur, District West Dinajpur - 733 125, West Bengal', 'West Dinajpur', 'West Bengal', '733125', 'PRIVATE'),
    ('Dewanhat Mahavidyalaya', 'West Bengal', 'Dewanhat, Cooch Behar, West Bengal - 736 134, West Bengal', null, 'West Bengal', '736134', 'PRIVATE'),
    ('Dinahata College', 'Dinahata', 'Dinahata, District Cooch Behar - 736 135, West Bengal', 'Cooch Behar', 'West Bengal', '736135', 'PRIVATE'),
    ('Falakata College', 'Falakata', 'Falakata, District Jalpaiguri - 735 211, West Bengal', 'Jalpaiguri', 'West Bengal', '735211', 'PRIVATE'),
    ('Gangarampur College', 'Gangarampur', 'Gangarampur, District South Dinajpur - 733 124, West Bengal', 'South Dinajpur', 'West Bengal', '733124', 'PRIVATE'),
    ('Gour Mahavidyalaya', 'Malda', 'Malda, District Malda - 732 142, West Bengal', 'Malda', 'West Bengal', '732142', 'PRIVATE'),
    ('Government Teachers'' Training College', 'Malda', 'Malda, District Malda - 732 101, West Bengal', 'Malda', 'West Bengal', '732101', 'GOVERNMENT'),
    ('Indian Institute of Legal Studies', 'Dagapur', 'Dagapur, Matigara, Dist. Darjeeling - 734 010, West Bengal', 'Darjeeling', 'West Bengal', '734010', 'PRIVATE'),
    ('Islampur College', 'West Dinajpur', 'Islampur, West Dinajpur - 733 202, West Bengal', null, 'West Bengal', '733202', 'PRIVATE'),
    ('Jalpaiguri Law College', 'P.O. & Dist. Jalpaiguri', 'P.O. & Dist. Jalpaiguri - 735 101, West Bengal', null, 'West Bengal', '735101', 'PRIVATE'),
    ('Kaliachak College', 'Kaliachak', 'P.O. Sultanganj, Kaliachak, West Bengal', null, 'West Bengal', null, 'GOVERNMENT'),
    ('Kalimpong College', 'Kalimpong', 'Kalimpong, District Darjeeling - 734 301, West Bengal', 'Darjeeling', 'West Bengal', '734301', 'PRIVATE'),
    ('Kalipada Ghosh Terai Mahavidyalaya', 'Bagdogra', 'Bagdogra, District Darjeeling, West Bengal', 'Darjeeling', 'West Bengal', null, 'PRIVATE'),
    ('Kaliyaganj College', 'Kaliyagand', 'Kaliyagand, District Uttar Dinajpur - 733 129, West Bengal', 'Uttar Dinajpur', 'West Bengal', '733129', 'PRIVATE'),
    ('Kureseong College', 'Kurseong', 'Kurseong, District Darjeeling - 734 203, West Bengal', 'Darjeeling', 'West Bengal', '734203', 'PRIVATE'),
    ('Malda College', 'Malda', 'Malda, District Malda - 732 101, West Bengal', 'Malda', 'West Bengal', '732101', 'PRIVATE'),
    ('Malda Women''s College', 'Malda', 'Malda, District Malda - 732 101, West Bengal', 'Malda', 'West Bengal', '732101', 'PRIVATE'),
    ('Mathabhanda College', 'Mathabhanga', 'Mathabhanga, District Cooch Behar - 736 146, West Bengal', 'Cooch Behar', 'West Bengal', '736146', 'PRIVATE'),
    ('Maynaguri College', 'Maynaguri', 'P.O.-Maynaguri, District Jalpaiguri-735 224, West Bengal', 'Jalpaiguri', 'West Bengal', '735224', 'PRIVATE'),
    ('Netaji Subash Chandra Mahavidyalaya', 'Cooach Behar', 'Cooach Behar, District Cooch Behar - 735 122, West Bengal', 'Cooch Behar', 'West Bengal', '735122', 'PRIVATE'),
    ('North Bengal Medical College', 'Darjeelijng', 'P.O. Shushrutanagar, Darjeelijng, District Darjeeling, West Bengal', 'Darjeeling', 'West Bengal', null, 'GOVERNMENT'),
    ('North Bengal University College', 'Rajaram Mohan Pur', 'Rajaram Mohan Pur, Darjeeling, West Bengal', null, 'West Bengal', null, 'GOVERNMENT'),
    ('Pakuahat Degree College', 'Pakuahat', 'P.O. Pakuahat, Dist. Malda - 732 138, West Bengal', 'Malda', 'West Bengal', '732138', 'GOVERNMENT'),
    ('Parimal Mitra Smriti Mahavidyalaya', 'Jalpaiguri', 'Jalpaiguri, District Jalpaiguri - 735 221, West Bengal', 'Jalpaiguri', 'West Bengal', '735221', 'PRIVATE'),
    ('Prasannadeb Women''s College', 'Jalpaiguri', 'Jalpaiguri, District Jalpaiguri - 735 101, West Bengal', 'Jalpaiguri', 'West Bengal', '735101', 'PRIVATE'),
    ('Raiganj Surendranath Mahavidyalaya', 'Raiganj', 'Raiganj, District North Dinapur - 733 134, West Bengal', 'North Dinapur', 'West Bengal', '733134', 'PRIVATE'),
    ('Raiganj University College', 'Raiganj', 'Raiganj, District Uttar Dinajpur - 733 134, West Bengal', 'Uttar Dinajpur', 'West Bengal', '733134', 'GOVERNMENT'),
    ('Salesian College', 'Sonada - 19', 'Sonada - 19, District Darjeeling, West Bengal', 'Darjeeling', 'West Bengal', null, 'PRIVATE'),
    ('Samsi College', 'Samsi', 'Samsi, District Malda - 732 139, West Bengal', 'Malda', 'West Bengal', '732139', 'PRIVATE'),
    ('Shahind Ksudiram College', 'Kakakshyaguri', 'P.O. Kakakshyaguri, District Jalpaiguri - 736 202, West Bengal', 'Jalpaiguri', 'West Bengal', '736202', 'PRIVATE'),
    ('Shree AgraseN Mahavidyalaya', 'Dalkhola', 'P.O. Dalkhola, West Bengal', null, 'West Bengal', null, 'PRIVATE'),
    ('Shri Agrasen Mahavidyalaya', 'Dalkhola', 'P.O. Dalkhola, District Uttar Dinajpur - 733 201, West Bengal', 'Uttar Dinajpur', 'West Bengal', '733201', 'PRIVATE'),
    ('Shri Rama Krishna B.T. College', 'Darjeeling', 'Darjeeling, District Darjeeling - 734 101, West Bengal', 'Darjeeling', 'West Bengal', '734101', 'PRIVATE'),
    ('Sikkim Government College', 'Gangtok', 'Gangtok - 737 102, West Bengal', null, 'West Bengal', '737102', 'GOVERNMENT'),
    ('Sikkim Government Law College', 'Gangtok', 'Gangtok - 731 101, West Bengal', null, 'West Bengal', '731101', 'GOVERNMENT'),
    ('Siliguri B.Ed. College', 'Shiv Mandir', 'Shiv Mandir, P.O. Kadamtala, District Darjeeling, West Bengal', 'Darjeeling', 'West Bengal', null, 'PRIVATE'),
    ('Siliguri College', 'Siliguri', 'P.O. Siliguri, District Darjeeling - 734 401, West Bengal', 'Darjeeling', 'West Bengal', '734401', 'PRIVATE'),
    ('Siliguri College of Commerce', 'Siliguri', 'Siliguri, District Darjeeling - 734 401, West Bengal', 'Darjeeling', 'West Bengal', '734401', 'PRIVATE'),
    ('Siliguri Mahila Mahavidyalaya', 'Siliguri, District Darjeeling', 'Dabgram Colony, No 1, P.O. Rabindra Sarani, Siliguri, District Darjeeling - 734 406, West Bengal', null, 'West Bengal', '734406', 'PRIVATE'),
    ('Sonada Degree College', 'Sonada', 'P.O. Sonada, Dist. Darjeeling - 734 219, West Bengal', 'Darjeeling', 'West Bengal', '734219', 'GOVERNMENT'),
    ('South Malda College', 'Purbarun', 'P.O. Purbarun, District Malda, West Bengal', 'Malda', 'West Bengal', null, 'PRIVATE'),
    ('Southfield College', 'Darjeeling', 'Darjeeling, District Darjeeling - 734 101, West Bengal', 'Darjeeling', 'West Bengal', '734101', 'PRIVATE'),
    ('St. Joseph''s College', 'Darjeeling', 'P.O. North Point, Darjeeling, District Darjeeling - 734 104, West Bengal', 'Darjeeling', 'West Bengal', '734104', 'PRIVATE'),
    ('Sukanta Mahavidyalaya', 'Dhupguri', 'Dhupguri, District Jalpaiguri - 735 210, West Bengal', 'Jalpaiguri', 'West Bengal', '735210', 'PRIVATE'),
    ('Surya Sen Mahavidyalaya', 'Siliguru', 'Siliguru - 734430, West Bengal', null, 'West Bengal', '734430', 'PRIVATE'),
    ('Surya Sen Mahavidyalaya', 'Siliguri', 'PO Siliguri, District Darjeeling - 734 404, West Bengal', 'Darjeeling', 'West Bengal', '734404', 'PRIVATE'),
    ('Thakur Panchanan Mahila Mahavidyalaya', 'Cooch Behar', 'Cooch Behar, District Cooch Behar - 736 101, West Bengal', 'Cooch Behar', 'West Bengal', '736101', 'PRIVATE'),
    ('Tufanganj College', 'Tufanganj', 'Tufanganj, District Cooch Behar - 736 160, West Bengal', 'Cooch Behar', 'West Bengal', '736160', 'PRIVATE'),
    ('University B.T. Evening College', 'Cooch Behar', 'Kalighat Road, Cooch Behar, District Cooch Behar - 736 101, West Bengal', 'Cooch Behar', 'West Bengal', '736101', 'GOVERNMENT'),
    ('Vivekananda College', 'Alipurduar', 'Alipurduar, Jalpaiguri, District Jalpaiguri - 736 121, West Bengal', 'Jalpaiguri', 'West Bengal', '736121', 'PRIVATE'),
    ('The Indian College of Arts and Draftmanship', 'Kolkata', 'Kolkata - 700074, West Bengal', null, 'West Bengal', '700074', 'PRIVATE'),
    ('Bajkul Milani Mahavidyalaya', 'Kismat - Bajkul', 'Kismat - Bajkul, District Midnapore, West Bengal', 'Midnapore', 'West Bengal', null, 'PRIVATE'),
    ('Belda College', 'Belda', 'Belda, District Midnapore - 721 424, West Bengal', 'Midnapore', 'West Bengal', '721424', 'PRIVATE'),
    ('Bhattar College', 'Dantan', 'Dantan, District Midnapore - 721 426, West Bengal', 'Midnapore', 'West Bengal', '721426', 'PRIVATE'),
    ('Chandrakona Vidyasagar Mahavidyalaya', 'Chandrakona', 'Chandrakona, District Midnapore, West Bengal', 'Midnapore', 'West Bengal', null, 'PRIVATE'),
    ('Debra Thana Sahid Kshudiram Smriti Mahavidyalaya', 'Chakshyampur', 'P.O. - Chakshyampur, Dist. Paschim Medinipur - 721 124, West Bengal', 'Paschim Medinipur', 'West Bengal', '721124', 'PRIVATE'),
    ('Egra Sarada Shasibhusan College', 'Egra', 'Egra, District Midnapore - 721 429, West Bengal', 'Midnapore', 'West Bengal', '721429', 'PRIVATE'),
    ('Garhbeta College', 'Garhbeta', 'Garhbeta, District Midnapore - 721 127, West Bengal', 'Midnapore', 'West Bengal', '721127', 'PRIVATE'),
    ('Gourav Guin Memorial College', 'Satbankura', 'Chandrakona Road, P.O. -, Satbankura, Dist - Paschim Medinipur - 721 253, West Bengal', 'Paschim Medinipur', 'West Bengal', '721253', 'GOVERNMENT'),
    ('Haldia Government College', 'Debhog', 'Debhog, District Midnapore, West Bengal', 'Midnapore', 'West Bengal', null, 'PRIVATE'),
    ('Hilji College', 'Kuchlachai', 'Kuchlachai, District Midnapore - 721 306, West Bengal', 'Midnapore', 'West Bengal', '721306', 'PRIVATE'),
    ('Institute of Education', 'Haldia', 'Haldia, Vill. Amlat, P.O. + P.S. - Sutahata, Dist. Purba Medinipur - 721 635, West Bengal', 'Purba Medinipur', 'West Bengal', '721635', 'PRIVATE'),
    ('Jhargram Raj College', 'Jhargram', 'Jhargram, District Midnapore - 721 507, West Bengal', 'Midnapore', 'West Bengal', '721507', 'PRIVATE'),
    ('Kaibalyadayini College of Commerce', 'Midnapore', 'Midnapore, District Midnapore - 721 101, West Bengal', 'Midnapore', 'West Bengal', '721101', 'PRIVATE'),
    ('Kharagpur College', 'Midnapore', 'Midnapore, District Midnapore - 721 305, West Bengal', 'Midnapore', 'West Bengal', '721305', 'PRIVATE'),
    ('Khejuri College', 'Medinipur', 'Baratala, District Purba, Medinipur-721 432, West Bengal', null, 'West Bengal', '721432', 'PRIVATE'),
    ('Maharaja Nandakumar Mahavidyalaya', 'Bhabanipur', 'Vill. Bhabanipur, P.O. - Kalyanchak, Dist. Purba Medinipur - 721 665, West Bengal', 'Purba Medinipur', 'West Bengal', '721665', 'PRIVATE'),
    ('Mahishadal''s Girls College', 'Mahishadal', 'Mahishadal, District Midnapore - 721 628, West Bengal', 'Midnapore', 'West Bengal', '721628', 'PRIVATE'),
    ('Mahishdal Raj College', 'Mahishadal', 'Mahishadal, District Midnapore - 721 628, West Bengal', 'Midnapore', 'West Bengal', '721628', 'PRIVATE'),
    ('Midnapore College', 'Midnapore', 'Midnapore, District Midnapore, West Bengal', 'Midnapore', 'West Bengal', null, 'PRIVATE'),
    ('Midnapore Law College', '102', 'P.O. Vidyasagar University - 721, 102, District Paschim Medinipur, West Bengal', 'Paschim Medinipur', 'West Bengal', null, 'PRIVATE'),
    ('Moyna College', 'Moyna', 'Moyna, District Midnapore - 721 401, West Bengal', 'Midnapore', 'West Bengal', '721401', 'PRIVATE'),
    ('Mugheria Gangadhar Mahavidyalaya', 'Bhupatinagar', 'P.O. Bhupatinagar, District Midnapore 721 425, West Bengal', 'Midnapore', 'West Bengal', '721425', 'PRIVATE'),
    ('Narajole Raj College', 'Narajole', 'Narajole, District Midnapore - 721 211, West Bengal', 'Midnapore', 'West Bengal', '721211', 'PRIVATE'),
    ('Panskura Banamali College', 'Panskura', 'Panskura, District Midnapore - 721 152, West Bengal', 'Midnapore', 'West Bengal', '721152', 'PRIVATE'),
    ('Pingla Thana Mahavidyalaya', 'Maligram', 'Maligram, District Midnapore -- 721 140, West Bengal', 'Midnapore', 'West Bengal', '721140', 'PRIVATE'),
    ('Prabhat kumar College', 'Contai', 'Contai, District Midnapore - 721 481, West Bengal', 'Midnapore', 'West Bengal', '721481', 'PRIVATE'),
    ('Rabindra Satabarsiki Mahavidyalaya', 'Ghatal', 'Ghatal, District Midnapore - 721 211, West Bengal', 'Midnapore', 'West Bengal', '721211', 'PRIVATE'),
    ('Raja Narendralal Khan Women''s College', 'Midnapore', 'Midnapore, District Midnapore - 721 102, West Bengal', 'Midnapore', 'West Bengal', '721102', 'PRIVATE'),
    ('Ramnagar College', 'Depal', 'Depal, District Midnapore - 721 453, West Bengal', 'Midnapore', 'West Bengal', '721453', 'PRIVATE'),
    ('Sabang Sajanikanta Mahavidyalaya', 'Lutunia', 'Lutunia, District Midnapore - 721 166, West Bengal', 'Midnapore', 'West Bengal', '721166', 'PRIVATE'),
    ('Santal Bidroha Sardha Satabarshiki Mahavidyalaya', 'Goaltore', 'P.O. Goaltore, Dist. Paschim Medinipur - 721 128, West Bengal', 'Paschim Medinipur', 'West Bengal', '721128', 'PRIVATE'),
    ('Seva Bharati Mahavidyalaya', 'Kapgari', 'P.O. Kapgari, District Midnapore - 721 505, West Bengal', 'Midnapore', 'West Bengal', '721505', 'PRIVATE'),
    ('Sevayatan Sikshan Mahavidyalaya', 'Jhargram', 'P.o. Jhargram, District Midnapore - 721 514, West Bengal', 'Midnapore', 'West Bengal', '721514', 'PRIVATE'),
    ('Silda Chandrasekhar College', 'Silda', 'Silda, District Midnapore - 721 515, West Bengal', 'Midnapore', 'West Bengal', '721515', 'PRIVATE'),
    ('Sitananda College', 'Nandigram', 'Nandigram, District Midnapore - 721 631, West Bengal', 'Midnapore', 'West Bengal', '721631', 'PRIVATE'),
    ('Subanarakha Mahavidyalaya', 'Gopiballavpur', 'Gopiballavpur, District Midnapore - 721 506, West Bengal', 'Midnapore', 'West Bengal', '721506', 'PRIVATE'),
    ('Tamralipta Mahavidyalaya', 'Tamluk', 'Tamluk, District Midnapore - 721 636, West Bengal', 'Midnapore', 'West Bengal', '721636', 'PRIVATE'),
    ('Vidyasagar School of Social Work', 'Kolkata', 'DD18/4/1, Salt lake City, Kolkata-700 064, West Bengal', null, 'West Bengal', '700064', 'PRIVATE'),
    ('Vidyasagar Teachers'' Training College', 'Midnapore', 'Midnapore, District Midnapore - 721 101, West Bengal', 'Midnapore', 'West Bengal', '721101', 'PRIVATE'),
    ('Vivekanand Setavarsiki Mahavidyalaya', 'Manikpara', 'Manikpara, District Midnapore, West Bengal', 'Midnapore', 'West Bengal', null, 'PRIVATE'),
    ('Vivekananda Mission Mahavidyaloaya', 'Vivekanagar', 'Vivekanagar, P.O. Chaitanyapur, District Midnapore - 721 645, West Bengal', 'Midnapore', 'West Bengal', '721645', 'PRIVATE'),
    ('Yogada Satsangha Palpara Mahavidyalaya', 'Palpara', 'Palpara, District Midnapore - 721 458, West Bengal', 'Midnapore', 'West Bengal', '721458', 'PRIVATE'),
    ('Acharya Prafulla Chandra College', 'New Barrackpore', 'New Barrackpore, District North Twenty Four Paraganas, West Bengal', 'North Twenty Four Paraganas', 'West Bengal', null, 'PRIVATE'),
    ('Bamanpukur Humayun Kabir Mahavidyalaya', 'North 24 Parganas', 'Bamanpukur, North 24 Parganas - 743 425, West Bengal', null, 'West Bengal', '743425', 'PRIVATE'),
    ('Banipur Mahila Mahavidyalaya', 'Habra Distt. North 24 Parganas - 743', 'P.O. - Banipur, Habra Distt. North 24 Parganas - 743, 233, West Bengal', null, 'West Bengal', null, 'PRIVATE'),
    ('Derozio Memorial College', 'R.Gopalpur North 24 Parganas', 'P.O.-R.Gopalpur North 24 Parganas-, 700 136, West Bengal', null, 'West Bengal', '700136', 'PRIVATE'),
    ('Dr. B.C. Roy Engineering College', 'Durgapur', 'Jemua Road, Fuljhere, Durgapur - 713 206, West Bengal', null, 'West Bengal', '713206', 'PRIVATE'),
    ('Haldia Institute of Technology', 'Hatiberia', 'Hatiberia - 721 657, Haldia, District Purba Medinipur, West Bengal', null, 'West Bengal', '721657', 'PRIVATE'),
    ('Hingalganj Mahavidyalaya', 'Hingalganj', 'P.O. Hingalganj, Dist. North 24 Parganas - 743 435, West Bengal', 'North 24 Parganas', 'West Bengal', '743435', 'PRIVATE'),
    ('Mrinalini Dutta Mahavidyapith', 'Calcutta', 'Vidyapith Road, Birati, Calcutta - 700 051, District North Twenty Four Parganas, West Bengal', 'North Twenty Four Parganas', 'West Bengal', '700051', 'PRIVATE'),
    ('Netaji Satabarshiki Mahavidyalaya', 'Ashoknagar', 'Ashoknagar, Sahidbag, P.O. Haripur, Dist. North - 24 Parganas- 743 223, West Bengal', 'North - 24 Parganas', 'West Bengal', '743223', 'PRIVATE'),
    ('Rama Krishna Mission Vivekananda Centenary College', 'Rahara', 'Rahara - 743 186, District North Twenty Four Parganas, West Bengal', 'North Twenty Four Parganas', 'West Bengal', '743186', 'PRIVATE'),
    ('Ramakrishna Mission Brahmananda College of Education', 'Kolkata', 'P.O. - Rahara, Kolkata - 700 118, West Bengal', null, 'West Bengal', '700118', 'PRIVATE'),
    ('Sitalkuchi College', 'Coochbehau', 'Sitalkuchi, Coochbehau - 736 158, West Bengal', null, 'West Bengal', '736158', 'PRIVATE'),
    ('Abacus Institute of Engineering and Management', 'Hooghly', 'Natungram, Mogra, Hooghly - 712 148, West Bengal', null, 'West Bengal', '712148', 'PRIVATE'),
    ('Asansol Engineering College', 'Kolkata', 'Chatterjee International Centre, 5th Floor, Flat No - 11, 33 A, Chowringhee Road, Kolkata - 700 071, West Bengal', null, 'West Bengal', '700071', 'PRIVATE'),
    ('Bankura Unnayani Institute of Engineering', 'Bankura', 'Pohabagan, Bankura - 722 146, West Bengal', null, 'West Bengal', '722146', 'PRIVATE'),
    ('Bengal Institute of Technology & Management', 'P.O.-Doranda', 'Santiniketan, BITM Campus, Sriniketan Bypass, P.O.-Doranda - 731 236, West Bengal', null, 'West Bengal', '731236', 'PRIVATE'),
    ('Birbhum Institute of Engineering and Technology', 'Suri', 'P.O. - Suri, Dist. Birbhum - 731 101, West Bengal', 'Birbhum', 'West Bengal', '731101', 'PRIVATE'),
    ('Calcutta Institute of Technology', 'Howrah', 'Uluberia, Howrah - 711 316, West Bengal', null, 'West Bengal', '711316', 'PRIVATE'),
    ('College of Engineering and Management', 'Kolaghat', 'Kolaghat, P.O. KTPP Township, Dist. Purba Medinipur - 721 171, West Bengal', 'Purba Medinipur', 'West Bengal', '721171', 'PRIVATE'),
    ('College of Textile Technology', 'Serampur, Hoogly', 'Serampur, Hoogly, West Bengal', null, 'West Bengal', null, 'GOVERNMENT'),
    ('Dr. Sudhir Chandra Sur Degree Engineering College', 'Kolkata', '540 Dum Dum Road, Surermath, Kolkata - 700 074, West Bengal', null, 'West Bengal', '700074', 'PRIVATE'),
    ('Government College of Engineering & Ceramic Technology', 'Calcutta - 10', '73, A.C. Banerjee Lane, Calcutta - 10, District Calcutta, West Bengal', 'Calcutta', 'West Bengal', null, 'GOVERNMENT'),
    ('Government College of Engineering and Leather Technology', 'Kolkata', 'Block LB, Sector - III, Salt Lake, Kolkata -  700 098, West Bengal', null, 'West Bengal', '700098', 'GOVERNMENT'),
    ('Gupta College of Technological Sciences', 'Asansol', 'Ashram More, G.T. Road, Asansol-713 303, West Bengal', null, 'West Bengal', '713303', 'PRIVATE'),
    ('Guru Nanak Institute of Hotel Management', 'Kolkata', '157/F, Nilgunj Road, Panihati, Kolkata - 700 114, West Bengal', null, 'West Bengal', '700114', 'PRIVATE'),
    ('Guru Nanak Institute of Technology', 'Panihati, Kolkata', '157/F, Nilgunj Road, Panihati, Kolkata - 700 114, West Bengal', null, 'West Bengal', '700114', 'PRIVATE'),
    ('Heritage Institute of Tech.', 'Anandpur', 'Chowbagh Road, Anandpur, P.O. East Kalkath Township, Kolkata, West Bengal', null, 'West Bengal', null, 'PRIVATE'),
    ('Hooghly Engineering & Technology College', 'P.O. & Dist. - Hooghly', 'Vivekananda Road, Pipulpati, P.O. & Dist. - Hooghly - 712 103, West Bengal', null, 'West Bengal', '712103', 'PRIVATE'),
    ('Institute of Genetic Engineering', 'Kolkata', 'Badu, Kolkata - 700 128, West Bengal', null, 'West Bengal', '700128', 'PRIVATE'),
    ('Institute of Management Study', 'Kolkata', 'Eastern Metropolitan Byepass, 93 Mukundapur Main Road, Kolkata - 700 099, West Bengal', null, 'West Bengal', '700099', 'PRIVATE'),
    ('Jalpaiguri Government Engineering College', 'Jalpaiguri', 'Jalpaiguri - 735 102, West Bengal', null, 'West Bengal', '735102', 'GOVERNMENT'),
    ('JIS College of Engineering', 'Nadia', 'Block A, Phase III, Kalyani, Nadia - 741 235, West Bengal', null, 'West Bengal', '741235', 'PRIVATE'),
    ('Kalyani Government Engineering College', 'Kalayani', 'Kalayani - 741 235, West Bengal', null, 'West Bengal', '741235', 'GOVERNMENT'),
    ('MCKV Institute of Engineering', 'Howrah', '243, G.T. Road (North), Liluah, Howrah - 711 204, West Bengal', null, 'West Bengal', '711204', 'PRIVATE'),
    ('Narula Institute of Technology', 'Agarpara, Kolkata', '81, Nilgunj Road, Agarpara, Kolkata - 700 109, West Bengal', null, 'West Bengal', '700109', 'PRIVATE'),
    ('NSHM College of Pharmaceutical Technology', 'Kolkata', 'Kolkata - 700 053, West Bengal', null, 'West Bengal', '700053', 'PRIVATE'),
    ('RCC Institute of Information Technology', 'Kolkata', 'Canal South Road, Beliaghata, Kolkata - 700 015, West Bengal', null, 'West Bengal', '700015', 'PRIVATE'),
    ('Supreme Knowledge Foundation Group of Institutions', 'Hooghly', '1, Khan Road, P.O. Mankundu, Hooghly - 712 139, West Bengal', null, 'West Bengal', '712139', 'PRIVATE')
  on conflict (name, place, pincode) do nothing;
