-- ============================================================================
-- 048_arith_problems_on_ages.sql
-- Question-bank seed: Arithmetic chapter "Problems on Ages" -- 36 single-answer MCQs
-- from ACTUAL previous-year papers (SBI/IBPS/RBI/Canara PO & Clerk, SSC CGL/CHSL,
-- TS/AP ICET, TCS NQT/Infosys/Wipro/Cognizant) via IndiaBix, PrepInsta, Testbook,
-- Adda247, Oliveboard, CareerPower, Examveda, 2IIM, GeeksforGeeks, Sawaal.
-- Ratio + past/future conditions, multi-person families, average + ratio.
-- Exam-grade difficulty floor; answers independently recomputed; 4 distinct-valued
-- options, one correct; each carries a worked explanation. Depends on 023. Reuses the
-- idempotent _seed_arith_q helper (dollar-quoted). Safe to re-run.
-- ============================================================================

create or replace function public._seed_arith_q(p_chapter text, p_difficulty text, p_stem text, p_opts text[], p_correct int, p_explanation text) returns void language plpgsql as $$
declare v_subj uuid; v_chap uuid; v_qid uuid; i int;
begin
  select id into v_subj from public.subject where lower(name)='arithmetic' limit 1;
  if v_subj is null then raise exception 'Arithmetic subject not found (run 023 first)'; end if;
  select id into v_chap from public.chapter where subject_id=v_subj and lower(name)=lower(p_chapter) limit 1;
  if v_chap is null then raise exception 'Chapter % not found', p_chapter; end if;
  if exists (select 1 from public.question where chapter_id=v_chap and stem=p_stem) then return; end if;
  insert into public.question (subject_id, chapter_id, kind, difficulty, answer_type, stem, explanation)
  values (v_subj, v_chap, 'standard', p_difficulty, 'single', p_stem, p_explanation) returning id into v_qid;
  for i in 1..array_length(p_opts,1) loop
    insert into public.question_option (question_id, label, is_correct, position) values (v_qid, p_opts[i], i=p_correct, i-1);
  end loop;
end; $$;

-- Problems on Ages (36 questions)
select public._seed_arith_q($q$Problems on Ages$q$,'easy',$q$The present ages of two friends are in the ratio 4 : 5 and the sum of their ages is 45 years. What is the age of the younger friend?$q$,array[$q$20 years$q$,$q$25 years$q$,$q$18 years$q$,$q$22 years$q$],1,$q$Let ages be 4x and 5x. 4x+5x=45 → 9x=45 → x=5. Younger = 4x = 20; older = 25 (sum 45). ✓$q$);
select public._seed_arith_q($q$Problems on Ages$q$,'easy',$q$Fifteen years hence a man's age will be five times his age five years ago. What is his present age?$q$,array[$q$8 years$q$,$q$10 years$q$,$q$12 years$q$,$q$15 years$q$],2,$q$Let present age = p. p+15 = 5(p−5) → p+15 = 5p−25 → 4p = 40 → p = 10. Check: 25 = 5×5. ✓$q$);
select public._seed_arith_q($q$Problems on Ages$q$,'easy',$q$The present age of a father is three times that of his son, and the sum of their present ages is 48 years. What is the son's present age?$q$,array[$q$16 years$q$,$q$10 years$q$,$q$12 years$q$,$q$14 years$q$],3,$q$Son = x, father = 3x. x+3x = 48 → 4x = 48 → x = 12. Father = 36. ✓$q$);
select public._seed_arith_q($q$Problems on Ages$q$,'easy',$q$A man's age 10 years ago was half of what it will be after 8 years. What is his present age?$q$,array[$q$24 years$q$,$q$26 years$q$,$q$28 years$q$,$q$30 years$q$],3,$q$Let present age = p. p−10 = ½(p+8) → 2(p−10) = p+8 → 2p−20 = p+8 → p = 28. Check: 18 = ½×36. ✓$q$);
select public._seed_arith_q($q$Problems on Ages$q$,'easy',$q$The present age of Mr. Sanyal is three times that of his son. Six years hence the ratio of their ages will be 5 : 2. What is Mr. Sanyal's present age?$q$,array[$q$48 years$q$,$q$54 years$q$,$q$60 years$q$,$q$51 years$q$],2,$q$Son = x, Sanyal = 3x. (3x+6)/(x+6) = 5/2 → 2(3x+6) = 5(x+6) → 6x+12 = 5x+30 → x = 18. Sanyal = 54. ✓$q$);
select public._seed_arith_q($q$Problems on Ages$q$,'easy',$q$At the time of his son's birth, a father was as old as his son is now. If the father is 38 years old today, what was the son's age 5 years ago?$q$,array[$q$14 years$q$,$q$16 years$q$,$q$19 years$q$,$q$24 years$q$],1,$q$Let son's present age = s. At the son's birth (s years ago) the father was s → 38−s = s → s = 19. Five years ago = 19−5 = 14. ✓$q$);
select public._seed_arith_q($q$Problems on Ages$q$,'easy',$q$The ages of two persons are in the ratio 3 : 5 and their difference is 12 years. What is the age of the elder person?$q$,array[$q$30 years$q$,$q$18 years$q$,$q$24 years$q$,$q$36 years$q$],1,$q$Ages 3x and 5x. 5x−3x = 12 → 2x = 12 → x = 6. Elder = 5x = 30; younger = 18. ✓$q$);
select public._seed_arith_q($q$Problems on Ages$q$,'easy',$q$Six years hence a girl's age will be four-thirds of her present age. What is her present age?$q$,array[$q$16 years$q$,$q$18 years$q$,$q$20 years$q$,$q$24 years$q$],2,$q$Let present age = p. p+6 = (4/3)p → 3(p+6) = 4p → 3p+18 = 4p → p = 18. Check: 24 = (4/3)×18. ✓$q$);
select public._seed_arith_q($q$Problems on Ages$q$,'easy',$q$A mother's age is seven times that of her daughter and the sum of their ages is 40 years. How old is the daughter?$q$,array[$q$4 years$q$,$q$5 years$q$,$q$6 years$q$,$q$8 years$q$],2,$q$Daughter = x, mother = 7x. x+7x = 40 → 8x = 40 → x = 5. Mother = 35. ✓$q$);
select public._seed_arith_q($q$Problems on Ages$q$,'medium',$q$The ratio of the present ages of two brothers is 5 : 7. After 6 years the ratio will become 3 : 4. Find their present ages.$q$,array[$q$30 and 42 years$q$,$q$25 and 35 years$q$,$q$20 and 28 years$q$,$q$35 and 49 years$q$],1,$q$Ages 5k and 7k. (5k+6)/(7k+6) = 3/4 → 4(5k+6) = 3(7k+6) → 20k+24 = 21k+18 → k = 6. Ages = 30 and 42. Check 36/48 = 3/4. ✓$q$);
select public._seed_arith_q($q$Problems on Ages$q$,'medium',$q$The ratio of the present ages of two colleagues is 3 : 4. Eight years ago the ratio was 5 : 8. Find their present ages.$q$,array[$q$18 and 24 years$q$,$q$15 and 20 years$q$,$q$21 and 28 years$q$,$q$24 and 32 years$q$],1,$q$Ages 3k and 4k. (3k−8)/(4k−8) = 5/8 → 8(3k−8) = 5(4k−8) → 24k−64 = 20k−40 → 4k = 24 → k = 6. Ages = 18 and 24. Check 10/16 = 5/8. ✓$q$);
select public._seed_arith_q($q$Problems on Ages$q$,'medium',$q$A person's present age is two-fifths of his mother's age. After 8 years he will be half his mother's age. What is the mother's present age?$q$,array[$q$36 years$q$,$q$40 years$q$,$q$44 years$q$,$q$48 years$q$],2,$q$Let mother = m, person = 2m/5. (2m/5+8)/(m+8) = 1/2 → 2(2m/5+8) = m+8 → 4m/5+16 = m+8 → 8 = m/5 → m = 40. ✓$q$);
select public._seed_arith_q($q$Problems on Ages$q$,'medium',$q$A son's present age is half of his mother's age. Ten years ago the mother was three times as old as the son. What is the son's present age?$q$,array[$q$18 years$q$,$q$20 years$q$,$q$22 years$q$,$q$24 years$q$],2,$q$Son = s, mother = 2s. 2s−10 = 3(s−10) → 2s−10 = 3s−30 → s = 20. Mother = 40. Check 10 yrs ago: 30 = 3×10. ✓$q$);
select public._seed_arith_q($q$Problems on Ages$q$,'medium',$q$Suresh's present age is twice that of his daughter. After 6 years the ratio of their ages will be 23 : 13. What is Suresh's present age?$q$,array[$q$36 years$q$,$q$38 years$q$,$q$40 years$q$,$q$44 years$q$],3,$q$Daughter = d, Suresh = 2d. (2d+6)/(d+6) = 23/13 → 13(2d+6) = 23(d+6) → 26d+78 = 23d+138 → 3d = 60 → d = 20. Suresh = 40. ✓$q$);
select public._seed_arith_q($q$Problems on Ages$q$,'medium',$q$A father is four times as old as his son. Five years hence the father will be three times as old as his son. What are their present ages?$q$,array[$q$40 and 10 years$q$,$q$36 and 9 years$q$,$q$44 and 11 years$q$,$q$32 and 8 years$q$],1,$q$Son = s, father = 4s. 4s+5 = 3(s+5) → 4s+5 = 3s+15 → s = 10. Father = 40. Check: 45 = 3×15. ✓$q$);
select public._seed_arith_q($q$Problems on Ages$q$,'medium',$q$The ratio of the present ages of A and B is 5 : 6. Seven years hence the ratio will be 6 : 7. What are their present ages?$q$,array[$q$30 and 36 years$q$,$q$35 and 42 years$q$,$q$25 and 30 years$q$,$q$40 and 48 years$q$],1,$q$Ages 5k and 6k. (5k+7)/(6k+7) = 6/7 → 7(5k+7) = 6(6k+7) → 35k+49 = 36k+42 → k = 7. Ages = 35 and 42. Wait: 5k=35, 6k=42. Check 42/49 = 6/7. ✓$q$);
select public._seed_arith_q($q$Problems on Ages$q$,'medium',$q$The present ages of three persons are in the ratio 4 : 7 : 9. Eight years ago the sum of their ages was 56 years. Find their present ages.$q$,array[$q$16, 28 and 36 years$q$,$q$12, 21 and 27 years$q$,$q$20, 35 and 45 years$q$,$q$8, 14 and 18 years$q$],1,$q$Ages 4k, 7k, 9k. (4k−8)+(7k−8)+(9k−8) = 56 → 20k−24 = 56 → 20k = 80 → k = 4. Ages = 16, 28, 36. ✓$q$);
select public._seed_arith_q($q$Problems on Ages$q$,'medium',$q$Rajan got married 8 years ago. His present age is 6/5 of his age at the time of marriage. Rajan's sister was 10 years younger to him at the time of his marriage. What is the present age of Rajan's sister?$q$,array[$q$32 years$q$,$q$36 years$q$,$q$38 years$q$,$q$40 years$q$],2,$q$Age at marriage = M. Now M+8 = (6/5)M → 8 = M/5 → M = 40. Sister at marriage = 30, now = 30+8 = 38. ✓$q$);
select public._seed_arith_q($q$Problems on Ages$q$,'hard',$q$Six years ago a father was three times as old as his son. Six years hence the father will be twice as old as his son. What are their present ages?$q$,array[$q$42 and 18 years$q$,$q$36 and 15 years$q$,$q$48 and 20 years$q$,$q$40 and 16 years$q$],1,$q$f−6 = 3(s−6) → f = 3s−12. f+6 = 2(s+6) → f = 2s+6. So 3s−12 = 2s+6 → s = 18, f = 42. Check hence: 48 = 2×24. ✓$q$);
select public._seed_arith_q($q$Problems on Ages$q$,'hard',$q$The present ages of three people are such that A is 2 years older than B, and B is twice as old as C. If the sum of their ages is 27 years, how old is B?$q$,array[$q$8 years$q$,$q$10 years$q$,$q$12 years$q$,$q$14 years$q$],2,$q$C = c, B = 2c, A = 2c+2. (2c+2)+2c+c = 27 → 5c+2 = 27 → c = 5. B = 10 (A=12, C=5). ✓$q$);
select public._seed_arith_q($q$Problems on Ages$q$,'hard',$q$Ten years ago a man was seven times as old as his son. Two years hence, twice the man's age will equal five times the son's age. What is the son's present age?$q$,array[$q$12 years$q$,$q$14 years$q$,$q$16 years$q$,$q$18 years$q$],2,$q$m−10 = 7(s−10) → m = 7s−60. 2(m+2) = 5(s+2) → 2(7s−58) = 5s+10 → 14s−116 = 5s+10 → 9s = 126 → s = 14 (m=38). Check: 2×40 = 80 = 5×16. ✓$q$);
select public._seed_arith_q($q$Problems on Ages$q$,'hard',$q$Six years ago the ratio of the ages of Kunal and Sagar was 6 : 5. Four years hence the ratio will be 11 : 10. What is Sagar's present age?$q$,array[$q$14 years$q$,$q$16 years$q$,$q$18 years$q$,$q$20 years$q$],2,$q$Six years ago: 6k and 5k, so now 6k+6 and 5k+6. (6k+10)/(5k+10) = 11/10 → 10(6k+10) = 11(5k+10) → 60k+100 = 55k+110 → 5k = 10 → k = 2. Sagar now = 5k+6 = 16. ✓$q$);
select public._seed_arith_q($q$Problems on Ages$q$,'hard',$q$X's age 3 years ago was three times the present age of Y. Z's present age is twice Y's present age, and Z is 12 years younger than X. What is Z's present age?$q$,array[$q$16 years$q$,$q$18 years$q$,$q$20 years$q$,$q$24 years$q$],2,$q$Let Y = y. X−3 = 3y → X = 3y+3. Z = 2y and Z = X−12 → 2y = 3y+3−12 → y = 9. Z = 18 (X = 30). Check: X−3 = 27 = 3×9; 30−12 = 18. ✓$q$);
select public._seed_arith_q($q$Problems on Ages$q$,'hard',$q$Ten years ago a father was thrice as old as his son. Ten years hence the father will be twice as old as his son. What is the ratio of their present ages?$q$,array[$q$5 : 2$q$,$q$7 : 3$q$,$q$3 : 1$q$,$q$9 : 4$q$],2,$q$f−10 = 3(s−10) → f = 3s−20. f+10 = 2(s+10) → f = 2s+10. So 3s−20 = 2s+10 → s = 30, f = 70. Ratio 70 : 30 = 7 : 3. ✓$q$);
select public._seed_arith_q($q$Problems on Ages$q$,'hard',$q$The sum of the present ages of a father and his son is 60 years. Six years ago the father was five times as old as his son. What will be the ratio of the son's age to the father's age six years from now?$q$,array[$q$5 : 13$q$,$q$1 : 3$q$,$q$2 : 5$q$,$q$3 : 7$q$],1,$q$f+s = 60 → f = 60−s. f−6 = 5(s−6) → 54−s = 5s−30 → 6s = 84 → s = 14, f = 46. Six years hence: son 20, father 52 → 20 : 52 = 5 : 13. ✓$q$);
select public._seed_arith_q($q$Problems on Ages$q$,'hard',$q$The present ages of a grandfather and grandson are such that 10 years ago the grandfather was seven times as old as the grandson, and 8 years hence he will be three times as old. What are their present ages?$q$,array[$q$73 and 19 years$q$,$q$70 and 18 years$q$,$q$68 and 17 years$q$,$q$75 and 20 years$q$],1,$q$g−10 = 7(t−10) → g = 7t−60. g+8 = 3(t+8) → 7t−52 = 3t+24 → 4t = 76 → t = 19, g = 73. Check hence: 81 = 3×27. ✓$q$);
select public._seed_arith_q($q$Problems on Ages$q$,'hard',$q$Rahul is as much younger than Sagar as he is older than Purav. The sum of the ages of Purav and Sagar is 66 years, and Sagar is 48 years old. What is the difference between the ages of Rahul and Purav?$q$,array[$q$12 years$q$,$q$15 years$q$,$q$18 years$q$,$q$9 years$q$],1,$q$Sagar−Rahul = Rahul−Purav → Rahul is the average of Sagar and Purav = (Sagar+Purav)/2 = 66/2 = 33. Purav = 66−48 = 18. Rahul−Purav = 33−18 = 15. ✓$q$);
select public._seed_arith_q($q$Problems on Ages$q$,'very_hard',$q$The average age of a family of four members was 24 years five years ago. Since then a baby was born, and today the average age of the family is still 24 years. What is the present age of the baby?$q$,array[$q$3 years$q$,$q$4 years$q$,$q$5 years$q$,$q$2 years$q$],2,$q$5 years ago total of 4 = 4×24 = 96. Today those four total 96+4×5 = 116. With baby b: (116+b)/5 = 24 → 116+b = 120 → b = 4. ✓$q$);
select public._seed_arith_q($q$Problems on Ages$q$,'very_hard',$q$The sum of the ages of five children born at intervals of 3 years each is 50 years. What is the age of the youngest child?$q$,array[$q$4 years$q$,$q$5 years$q$,$q$6 years$q$,$q$3 years$q$],1,$q$Ages: a, a+3, a+6, a+9, a+12. Sum = 5a+30 = 50 → 5a = 20 → a = 4. ✓$q$);
select public._seed_arith_q($q$Problems on Ages$q$,'very_hard',$q$Three years ago the average age of a husband and wife was 25 years. A child was born, and today the average age of the family of three is 20 years. What is the present age of the child?$q$,array[$q$2 years$q$,$q$3 years$q$,$q$4 years$q$,$q$5 years$q$],3,$q$3 years ago husband+wife = 2×25 = 50. Today they total 50+2×3 = 56. With child c: (56+c)/3 = 20 → 56+c = 60 → c = 4. ✓$q$);
select public._seed_arith_q($q$Problems on Ages$q$,'very_hard',$q$The ages of a father and his daughter average 34 years. The ratio of their ages 4 years from now will be 14 : 5. What is the daughter's present age?$q$,array[$q$14 years$q$,$q$15 years$q$,$q$16 years$q$,$q$18 years$q$],3,$q$Sum = 68. Let father m, daughter d, m+d = 68. (m+4)/(d+4) = 14/5 → 5(m+4) = 14(d+4). With m = 68−d: 5(72−d) = 14d+56 → 360−5d = 14d+56 → 19d = 304 → d = 16 (m=52). Check 56/20 = 14/5. ✓$q$);
select public._seed_arith_q($q$Problems on Ages$q$,'very_hard',$q$The present ages of three persons A, B and C are in the ratio 3 : 5 : 7 and their average age is 30 years. What is the age of the eldest?$q$,array[$q$42 years$q$,$q$35 years$q$,$q$45 years$q$,$q$36 years$q$],1,$q$Sum = 3×30 = 90. 3k+5k+7k = 15k = 90 → k = 6. Eldest = 7k = 42 (others 18, 30). ✓$q$);
select public._seed_arith_q($q$Problems on Ages$q$,'very_hard',$q$A man married at the age of 27. Five years into the marriage a child was born to him. When the child turns 8, the ratio of the man's age to the child's age is 5 : 1. What is the man's present age (when the child is 8)?$q$,array[$q$36 years$q$,$q$38 years$q$,$q$40 years$q$,$q$42 years$q$],3,$q$Man at marriage 27; child born when man is 27+5 = 32; when child is 8, man = 32+8 = 40. Ratio 40 : 8 = 5 : 1. ✓$q$);
select public._seed_arith_q($q$Problems on Ages$q$,'very_hard',$q$The ages of a grandfather, father and son are such that the son's age is half the father's, and the father's age is half the grandfather's. If the sum of their ages is 105 years, what are their ages?$q$,array[$q$60, 30 and 15 years$q$,$q$64, 32 and 16 years$q$,$q$72, 36 and 18 years$q$,$q$56, 28 and 14 years$q$],1,$q$Grandfather g, father g/2, son g/4. g + g/2 + g/4 = 105 → 7g/4 = 105 → g = 60. Father 30, son 15. ✓$q$);
select public._seed_arith_q($q$Problems on Ages$q$,'very_hard',$q$In a family the father is twice as old as his son, and the mother is 22 years older than the son. If the father's age equals the mother's age plus 4 years, what will be the father's age after 4 years?$q$,array[$q$52 years$q$,$q$54 years$q$,$q$56 years$q$,$q$58 years$q$],2,$q$Son s, father 2s, mother s+22, and father = mother+4 → 2s = (s+22)+4 → s = 26. Father = 52; after 4 years = 56 (mother 48). ✓$q$);
select public._seed_arith_q($q$Problems on Ages$q$,'very_hard',$q$The present ages of A and B are in the ratio 3 : 5. Five years hence the sum of their ages will be 66 years. If C's age is the average of A's and B's present ages, what is C's present age?$q$,array[$q$24 years$q$,$q$26 years$q$,$q$28 years$q$,$q$30 years$q$],3,$q$A = 3k, B = 5k. (3k+5)+(5k+5) = 66 → 8k+10 = 66 → k = 7. A = 21, B = 35. C = (21+35)/2 = 28. ✓$q$);

drop function public._seed_arith_q(text,text,text,text[],int,text);
