-- ============================================================================
-- 052_arith_profit_and_loss.sql
-- Question-bank seed: Arithmetic chapter "Profit and Loss" -- 36 single-answer MCQs
-- from ACTUAL previous-year papers (SBI/IBPS/RBI/Canara PO & Clerk, SSC CGL/CHSL,
-- TS/AP ICET, TCS NQT/Infosys/Wipro/Cognizant) via IndiaBix, PrepInsta, Testbook,
-- Adda247, Oliveboard, CareerPower, Examveda, 2IIM, GeeksforGeeks, Sawaal.
-- CP/SP, markup & successive discounts, false weights, same-SP trap, profit chains.
-- Exam-grade difficulty floor; answers independently recomputed; 4 distinct-valued
-- options, one correct; each carries a worked explanation. Depends on 023. Reuses the
-- idempotent _seed_arith_q helper (dollar-quoted). Safe to re-run.
-- ============================================================================

create or replace function public._seed_arith_q(p_chapter text, p_difficulty text, p_stem text, p_opts text[], p_correct int, p_explanation text) returns void language plpgsql as $$
declare v_subj uuid; v_chap uuid; v_qid uuid; i int;
begin
  select id into v_subj from public.subject where lower(name)='arithmetic' limit 1;
  if v_subj is null then raise exception 'Arithmetic subject not found (run 023 first)'; end if;
  select id into v_chap from public.chapter where subject_id=v_subj and lower(name)=lower(p_chapter) limit 1;
  if v_chap is null then raise exception 'Chapter % not found', p_chapter; end if;
  if exists (select 1 from public.question where chapter_id=v_chap and stem=p_stem) then return; end if;
  insert into public.question (subject_id, chapter_id, kind, difficulty, answer_type, stem, explanation)
  values (v_subj, v_chap, 'standard', p_difficulty, 'single', p_stem, p_explanation) returning id into v_qid;
  for i in 1..array_length(p_opts,1) loop
    insert into public.question_option (question_id, label, is_correct, position) values (v_qid, p_opts[i], i=p_correct, i-1);
  end loop;
end; $$;

-- Profit and Loss (36 questions)
select public._seed_arith_q($q$Profit and Loss$q$,'easy',$q$An article is bought for Rs. 400 and sold for Rs. 460. Find the profit percent.$q$,array[$q$12%$q$,$q$15%$q$,$q$20%$q$,$q$25%$q$],2,$q$Profit = 460 − 400 = 60. Profit% = 60/400 × 100 = 15%.$q$);
select public._seed_arith_q($q$Profit and Loss$q$,'easy',$q$By selling an article for Rs. 720, a man gains 20%. Find the cost price.$q$,array[$q$Rs. 576$q$,$q$Rs. 600$q$,$q$Rs. 640$q$,$q$Rs. 660$q$],2,$q$CP = SP/(1+gain) = 720/1.20 = Rs. 600.$q$);
select public._seed_arith_q($q$Profit and Loss$q$,'easy',$q$A shopkeeper buys a fan for Rs. 1200 and sells it for Rs. 1020. Find the loss percent.$q$,array[$q$12%$q$,$q$15%$q$,$q$18%$q$,$q$20%$q$],2,$q$Loss = 1200 − 1020 = 180. Loss% = 180/1200 × 100 = 15%.$q$);
select public._seed_arith_q($q$Profit and Loss$q$,'easy',$q$A trader sells goods at a loss of 10%. If his cost price was Rs. 800, what is the selling price?$q$,array[$q$Rs. 700$q$,$q$Rs. 710$q$,$q$Rs. 720$q$,$q$Rs. 740$q$],3,$q$SP = CP × (1 − loss) = 800 × 0.90 = Rs. 720.$q$);
select public._seed_arith_q($q$Profit and Loss$q$,'easy',$q$A dealer earns a profit of Rs. 150 on an article whose cost price is Rs. 600. Find the profit percent.$q$,array[$q$20%$q$,$q$22.5%$q$,$q$25%$q$,$q$30%$q$],3,$q$Profit% = 150/600 × 100 = 25%.$q$);
select public._seed_arith_q($q$Profit and Loss$q$,'easy',$q$An item is sold at Rs. 315, incurring a loss of 10%. Find its cost price.$q$,array[$q$Rs. 330$q$,$q$Rs. 340$q$,$q$Rs. 350$q$,$q$Rs. 360$q$],3,$q$CP = SP/(1 − loss) = 315/0.90 = Rs. 350.$q$);
select public._seed_arith_q($q$Profit and Loss$q$,'easy',$q$A pen costs Rs. 25 and is sold for Rs. 30. Find the gain percent.$q$,array[$q$16%$q$,$q$18%$q$,$q$20%$q$,$q$24%$q$],3,$q$Gain = 30 − 25 = 5. Gain% = 5/25 × 100 = 20%.$q$);
select public._seed_arith_q($q$Profit and Loss$q$,'easy',$q$On selling an article a shopkeeper makes a profit of 8%, which amounts to Rs. 40. Find the cost price.$q$,array[$q$Rs. 450$q$,$q$Rs. 480$q$,$q$Rs. 500$q$,$q$Rs. 520$q$],3,$q$8% of CP = 40 → CP = 40/0.08 = Rs. 500.$q$);
select public._seed_arith_q($q$Profit and Loss$q$,'easy',$q$A cycle is sold for Rs. 924 at a gain of 12%. What was the cost price?$q$,array[$q$Rs. 800$q$,$q$Rs. 812$q$,$q$Rs. 825$q$,$q$Rs. 840$q$],3,$q$CP = 924/1.12 = Rs. 825.$q$);
select public._seed_arith_q($q$Profit and Loss$q$,'medium',$q$A shopkeeper wants to earn a profit of 25% on an article that cost him Rs. 360. At what price should he sell it?$q$,array[$q$Rs. 420$q$,$q$Rs. 440$q$,$q$Rs. 450$q$,$q$Rs. 480$q$],3,$q$SP = 360 × 1.25 = Rs. 450.$q$);
select public._seed_arith_q($q$Profit and Loss$q$,'medium',$q$An article marked at Rs. 800 is sold after a discount of 10%. If it cost the trader Rs. 600, find his profit percent.$q$,array[$q$15%$q$,$q$18%$q$,$q$20%$q$,$q$24%$q$],3,$q$SP = 800 × 0.90 = 720. Profit% = (720 − 600)/600 × 100 = 20%.$q$);
select public._seed_arith_q($q$Profit and Loss$q$,'medium',$q$By selling an article for Rs. 810 a man loses 10%. At what price must he sell it to gain 8%?$q$,array[$q$Rs. 918$q$,$q$Rs. 945$q$,$q$Rs. 972$q$,$q$Rs. 990$q$],3,$q$CP = 810/0.90 = 900. SP for 8% gain = 900 × 1.08 = Rs. 972.$q$);
select public._seed_arith_q($q$Profit and Loss$q$,'medium',$q$A trader marks his goods 25% above cost price and then allows a discount of 10%. What is his profit percent?$q$,array[$q$10%$q$,$q$12.5%$q$,$q$15%$q$,$q$12%$q$],2,$q$Take CP = 100 → MP = 125 → SP = 125 × 0.90 = 112.5. Profit% = 12.5%.$q$);
select public._seed_arith_q($q$Profit and Loss$q$,'medium',$q$Two articles are each sold for Rs. 960; on one there is a profit of 20% and on the other a loss of 20%. Find the overall profit or loss percent.$q$,array[$q$No profit no loss$q$,$q$4% loss$q$,$q$4% profit$q$,$q$2% loss$q$],2,$q$For equal SP with ±x%, net is always a loss of (x/10)² = (20/10)² = 4% loss.$q$);
select public._seed_arith_q($q$Profit and Loss$q$,'medium',$q$A watch is sold at a gain of 20% for Rs. 1080. If it is sold so as to gain 30%, what will be the selling price?$q$,array[$q$Rs. 1120$q$,$q$Rs. 1150$q$,$q$Rs. 1170$q$,$q$Rs. 1200$q$],3,$q$CP = 1080/1.20 = 900. SP for 30% gain = 900 × 1.30 = Rs. 1170.$q$);
select public._seed_arith_q($q$Profit and Loss$q$,'medium',$q$A man sold an article at a loss of 10%. Had he sold it for Rs. 80 more, he would have gained 6%. Find the cost price.$q$,array[$q$Rs. 450$q$,$q$Rs. 480$q$,$q$Rs. 500$q$,$q$Rs. 520$q$],3,$q$The Rs. 80 difference corresponds to (6% + 10%) = 16% of CP. CP = 80/0.16 = Rs. 500.$q$);
select public._seed_arith_q($q$Profit and Loss$q$,'medium',$q$A vendor buys pens at 20 for Rs. 100 and sells them at 16 for Rs. 100. Find his profit percent.$q$,array[$q$20%$q$,$q$22%$q$,$q$25%$q$,$q$30%$q$],3,$q$CP/pen = 5, SP/pen = 100/16 = 6.25. Profit% = (6.25 − 5)/5 × 100 = 25%.$q$);
select public._seed_arith_q($q$Profit and Loss$q$,'medium',$q$After allowing a discount of 20% on the marked price, a shopkeeper still gains 12%. By what percent is the marked price above the cost price?$q$,array[$q$32%$q$,$q$35%$q$,$q$38%$q$,$q$40%$q$],4,$q$MP × 0.80 = CP × 1.12 → MP/CP = 1.12/0.80 = 1.40, i.e. 40% above CP.$q$);
select public._seed_arith_q($q$Profit and Loss$q$,'hard',$q$A shirt is marked at Rs. 500 and sold after two successive discounts of 20% and 10%. Find the selling price.$q$,array[$q$Rs. 350$q$,$q$Rs. 360$q$,$q$Rs. 370$q$,$q$Rs. 400$q$],2,$q$SP = 500 × 0.80 × 0.90 = Rs. 360.$q$);
select public._seed_arith_q($q$Profit and Loss$q$,'hard',$q$A dishonest dealer sells goods at cost price but uses a weight of 900 g in place of 1 kg. Find his profit percent.$q$,array[$q$9%$q$,$q$10%$q$,$q$11 1/9%$q$,$q$12 1/2%$q$],3,$q$He gives 900 g but charges for 1000 g. Profit% = (1000 − 900)/900 × 100 = 100/9 = 11 1/9%.$q$);
select public._seed_arith_q($q$Profit and Loss$q$,'hard',$q$A trader marks his goods 40% above cost price and allows a discount of 10% on the marked price. Find his profit percent.$q$,array[$q$24%$q$,$q$26%$q$,$q$28%$q$,$q$30%$q$],2,$q$CP = 100 → MP = 140 → SP = 140 × 0.90 = 126. Profit% = 26%.$q$);
select public._seed_arith_q($q$Profit and Loss$q$,'hard',$q$Two articles are each sold for Rs. 1200; one at a profit of 25% and the other at a loss of 25%. Find the net profit or loss percent.$q$,array[$q$6.25% loss$q$,$q$6.25% profit$q$,$q$No profit no loss$q$,$q$5% loss$q$],1,$q$Equal SP with ±25% gives net loss (25/10)² = 6.25%. Check: CP = 1200/1.25 + 1200/0.75 = 960 + 1600 = 2560; SP = 2400; loss = 160/2560 = 6.25%.$q$);
select public._seed_arith_q($q$Profit and Loss$q$,'hard',$q$A sells an article to B at a profit of 20% and B sells it to C at a profit of 25%. If C pays Rs. 1500, what did the article cost A?$q$,array[$q$Rs. 900$q$,$q$Rs. 1000$q$,$q$Rs. 1100$q$,$q$Rs. 1200$q$],2,$q$A's CP = 1500 / 1.25 / 1.20 = 1500/1.5 = Rs. 1000.$q$);
select public._seed_arith_q($q$Profit and Loss$q$,'hard',$q$A dishonest shopkeeper uses a false weight of 800 g for 1 kg and also marks up his goods by 12% over cost. Find his overall profit percent.$q$,array[$q$36%$q$,$q$38%$q$,$q$40%$q$,$q$42%$q$],3,$q$For 800 g he collects the price of 1000 g at a 12% markup: revenue = 1000 × 1.12 = 1120 per 800 g of actual cost 800. Profit% = (1120 − 800)/800 × 100 = 40%.$q$);
select public._seed_arith_q($q$Profit and Loss$q$,'hard',$q$A fruit-seller buys apples at 6 for a rupee and sells them at 4 for a rupee. Find his profit percent.$q$,array[$q$33 1/3%$q$,$q$40%$q$,$q$50%$q$,$q$60%$q$],3,$q$CP/apple = 1/6, SP/apple = 1/4. Profit% = (1/4 − 1/6)/(1/6) × 100 = (1/12)/(1/6) × 100 = 50%.$q$);
select public._seed_arith_q($q$Profit and Loss$q$,'hard',$q$An article costing Rs. 1000 is marked up 20% and then sold after two successive discounts of 10% and 5%. Find the profit percent.$q$,array[$q$2.6%$q$,$q$3.4%$q$,$q$4%$q$,$q$5%$q$],1,$q$SP = 1000 × 1.20 × 0.90 × 0.95 = 1026. Profit% = 2.6%.$q$);
select public._seed_arith_q($q$Profit and Loss$q$,'hard',$q$A merchant sells two-thirds of his stock at a profit of 20% and the remaining one-third at a loss of 20%. Find his overall profit or loss percent.$q$,array[$q$6 2/3% profit$q$,$q$6 2/3% loss$q$,$q$No profit no loss$q$,$q$4% profit$q$],1,$q$On CP 1: revenue = (2/3)(1.2) + (1/3)(0.8) = 0.8 + 0.2667 = 1.0667. Overall profit% = 6 2/3%.$q$);
select public._seed_arith_q($q$Profit and Loss$q$,'very_hard',$q$If the cost price of 15 articles is equal to the selling price of 12 articles, find the gain percent.$q$,array[$q$20%$q$,$q$22.5%$q$,$q$25%$q$,$q$30%$q$],3,$q$Let CP/article = 1. Then SP of 12 = 15, so SP/article = 15/12 = 1.25. Gain% = 25%.$q$);
select public._seed_arith_q($q$Profit and Loss$q$,'very_hard',$q$If the selling price of 16 articles equals the cost price of 12 articles, find the loss percent.$q$,array[$q$20%$q$,$q$25%$q$,$q$30%$q$,$q$33 1/3%$q$],2,$q$Let CP/article = 1. SP of 16 = 12 → SP/article = 12/16 = 0.75. Loss% = 25%.$q$);
select public._seed_arith_q($q$Profit and Loss$q$,'very_hard',$q$The profit on an article is 20% of its selling price. What is the profit percent calculated on the cost price?$q$,array[$q$20%$q$,$q$22%$q$,$q$25%$q$,$q$30%$q$],3,$q$Profit on SP conversion: profit%(on CP) = (0.2)/(1 − 0.2) × 100 = 0.2/0.8 × 100 = 25%.$q$);
select public._seed_arith_q($q$Profit and Loss$q$,'very_hard',$q$A dishonest trader sells his goods at cost price but gains 25% by using a false weight in place of 1 kg. What weight (in grams) does he actually use?$q$,array[$q$750 g$q$,$q$775 g$q$,$q$800 g$q$,$q$850 g$q$],3,$q$Selling at CP, profit comes only from short weight: 1000/w = 1.25 → w = 1000/1.25 = 800 g.$q$);
select public._seed_arith_q($q$Profit and Loss$q$,'very_hard',$q$A sells an article to B at a profit of 20% and B sells it to C at a loss of 10%. If C pays Rs. 1080, find the cost price to A.$q$,array[$q$Rs. 960$q$,$q$Rs. 1000$q$,$q$Rs. 1080$q$,$q$Rs. 1200$q$],2,$q$A's CP = 1080 / 0.90 / 1.20 = 1200/1.20 = Rs. 1000.$q$);
select public._seed_arith_q($q$Profit and Loss$q$,'very_hard',$q$A man sold a watch at a loss of 10%. Had he sold it for Rs. 140 more, he would have gained 15%. Find the cost price of the watch.$q$,array[$q$Rs. 520$q$,$q$Rs. 540$q$,$q$Rs. 560$q$,$q$Rs. 600$q$],3,$q$The Rs. 140 difference = (15% + 10%) = 25% of CP. CP = 140/0.25 = Rs. 560.$q$);
select public._seed_arith_q($q$Profit and Loss$q$,'very_hard',$q$A shopkeeper sells at a profit of 10% and also uses a weight of 800 g instead of 1 kg. Find his net profit percent.$q$,array[$q$32.5%$q$,$q$35%$q$,$q$37.5%$q$,$q$40%$q$],3,$q$For 800 g cost he charges the 10%-marked-up price of 1000 g: revenue = 1000 × 1.10 = 1100 per actual cost 800. Profit% = (1100 − 800)/800 × 100 = 37.5%.$q$);
select public._seed_arith_q($q$Profit and Loss$q$,'very_hard',$q$A reduction of 20% in the price of sugar enables a housewife to buy 4 kg more for Rs. 160. Find the reduced rate per kg.$q$,array[$q$Rs. 6$q$,$q$Rs. 7.50$q$,$q$Rs. 8$q$,$q$Rs. 10$q$],3,$q$Let original rate = x. 160/(0.8x) − 160/x = 4 → 200/x − 160/x = 4 → 40/x = 4 → x = 10; reduced rate = 0.8 × 10 = Rs. 8.$q$);
select public._seed_arith_q($q$Profit and Loss$q$,'very_hard',$q$An article is marked up 50% above its cost and then sold after two successive discounts of 20% and 25%. Find the resulting profit or loss percent.$q$,array[$q$10% loss$q$,$q$10% profit$q$,$q$5% loss$q$,$q$No profit no loss$q$],1,$q$CP = 100 → MP = 150 → SP = 150 × 0.80 × 0.75 = 90. Loss% = 10%.$q$);

drop function public._seed_arith_q(text,text,text,text[],int,text);
