-- ============================================================================
-- 056_arith_pipes_and_cisterns.sql
-- Question-bank seed: Arithmetic chapter "Pipes and Cisterns" -- 38 single-answer MCQs
-- from ACTUAL previous-year papers (SBI/IBPS/RBI/Canara PO & Clerk, SSC CGL/CHSL,
-- TS/AP ICET, TCS NQT/Infosys/Wipro/Cognizant) via IndiaBix, PrepInsta, Testbook,
-- Adda247, Oliveboard, CareerPower, Examveda, 2IIM, GeeksforGeeks, Sawaal.
-- Fill/empty rates, leaks, pipes closed partway, alternate pipes, capacity via L/min.
-- Exam-grade floor; answers independently recomputed; 4 distinct-valued options,
-- one correct; each carries a worked explanation. Depends on 023. Reuses the
-- idempotent _seed_arith_q helper (dollar-quoted). Safe to re-run.
-- ============================================================================

create or replace function public._seed_arith_q(p_chapter text, p_difficulty text, p_stem text, p_opts text[], p_correct int, p_explanation text) returns void language plpgsql as $$
declare v_subj uuid; v_chap uuid; v_qid uuid; i int;
begin
  select id into v_subj from public.subject where lower(name)='arithmetic' limit 1;
  if v_subj is null then raise exception 'Arithmetic subject not found (run 023 first)'; end if;
  select id into v_chap from public.chapter where subject_id=v_subj and lower(name)=lower(p_chapter) limit 1;
  if v_chap is null then raise exception 'Chapter % not found', p_chapter; end if;
  if exists (select 1 from public.question where chapter_id=v_chap and stem=p_stem) then return; end if;
  insert into public.question (subject_id, chapter_id, kind, difficulty, answer_type, stem, explanation)
  values (v_subj, v_chap, 'standard', p_difficulty, 'single', p_stem, p_explanation) returning id into v_qid;
  for i in 1..array_length(p_opts,1) loop
    insert into public.question_option (question_id, label, is_correct, position) values (v_qid, p_opts[i], i=p_correct, i-1);
  end loop;
end; $$;

-- Pipes and Cisterns (38 questions)
select public._seed_arith_q($q$Pipes and Cisterns$q$,'easy',$q$Pipe A can fill a tank in 20 minutes and pipe B in 30 minutes. If both are opened together, in how much time will the tank be full?$q$,array[$q$10 min$q$,$q$12 min$q$,$q$15 min$q$,$q$18 min$q$],2,$q$Combined rate = 1/20 + 1/30 = 5/60 = 1/12. Time = 12 min.$q$);
select public._seed_arith_q($q$Pipes and Cisterns$q$,'easy',$q$Pipe A fills a cistern in 6 hours and pipe B in 8 hours. Working together, how long to fill it?$q$,array[$q$3 3/7 h$q$,$q$4 h$q$,$q$2 6/7 h$q$,$q$3 h$q$],1,$q$1/6 + 1/8 = 7/24; time = 24/7 = 3 3/7 h.$q$);
select public._seed_arith_q($q$Pipes and Cisterns$q$,'easy',$q$A fill pipe fills a tank in 10 hours; an outlet empties a full tank in 15 hours. If both are open, how long to fill the empty tank?$q$,array[$q$25 h$q$,$q$30 h$q$,$q$20 h$q$,$q$6 h$q$],2,$q$Net = 1/10 − 1/15 = 1/30; time = 30 h.$q$);
select public._seed_arith_q($q$Pipes and Cisterns$q$,'easy',$q$Two pipes can fill a tank in 12 hours and 16 hours respectively. If both are opened together, in what time will the tank be filled?$q$,array[$q$6 6/7 h$q$,$q$7 h$q$,$q$6 h$q$,$q$8 h$q$],1,$q$1/12 + 1/16 = 7/48; time = 48/7 = 6 6/7 h.$q$);
select public._seed_arith_q($q$Pipes and Cisterns$q$,'easy',$q$Pipe A can fill a tank in 4 hours and pipe B in 6 hours. How long will both together take to fill it?$q$,array[$q$2 h$q$,$q$2.4 h$q$,$q$3 h$q$,$q$2.5 h$q$],2,$q$1/4 + 1/6 = 5/12; time = 12/5 = 2.4 h.$q$);
select public._seed_arith_q($q$Pipes and Cisterns$q$,'easy',$q$An inlet pipe fills a tank in 5 hours; an outlet empties it in 20 hours. With both open, time to fill the empty tank?$q$,array[$q$4 h$q$,$q$20/3 h$q$,$q$25/3 h$q$,$q$15/2 h$q$],2,$q$Net = 1/5 − 1/20 = 3/20; time = 20/3 h.$q$);
select public._seed_arith_q($q$Pipes and Cisterns$q$,'easy',$q$Two taps fill a bath in 15 minutes and 10 minutes respectively. Together, how long to fill the bath?$q$,array[$q$6 min$q$,$q$5 min$q$,$q$12 min$q$,$q$25 min$q$],1,$q$1/15 + 1/10 = 5/30 = 1/6; time = 6 min.$q$);
select public._seed_arith_q($q$Pipes and Cisterns$q$,'easy',$q$Pipe A fills a tank in 9 hours and pipe B in 18 hours. If both are opened together, in how many hours is the tank filled?$q$,array[$q$4 h$q$,$q$5 h$q$,$q$6 h$q$,$q$13.5 h$q$],3,$q$1/9 + 1/18 = 3/18 = 1/6; time = 6 h.$q$);
select public._seed_arith_q($q$Pipes and Cisterns$q$,'easy',$q$A pipe fills a cistern in 8 hours; a waste pipe empties the full cistern in 24 hours. Both open, time to fill?$q$,array[$q$16 h$q$,$q$10 h$q$,$q$12 h$q$,$q$6 h$q$],3,$q$Net = 1/8 − 1/24 = 2/24 = 1/12; time = 12 h.$q$);
select public._seed_arith_q($q$Pipes and Cisterns$q$,'easy',$q$Two pipes together fill a tank in 6 hours. If one pipe alone fills it in 10 hours, in what time does the other alone fill it?$q$,array[$q$15 h$q$,$q$16 h$q$,$q$4 h$q$,$q$12 h$q$],1,$q$1/6 − 1/10 = 2/30 = 1/15; other = 15 h.$q$);
select public._seed_arith_q($q$Pipes and Cisterns$q$,'medium',$q$A pipe can fill a tank in 4 hours, but due to a leak it takes 5 hours. In how many hours will the leak empty the full tank?$q$,array[$q$15 h$q$,$q$20 h$q$,$q$25 h$q$,$q$10 h$q$],2,$q$Leak rate = 1/4 − 1/5 = 1/20; leak empties in 20 h.$q$);
select public._seed_arith_q($q$Pipes and Cisterns$q$,'medium',$q$A cistern is normally filled in 6 hours, but a leak in the bottom makes it take 10 hours. In what time will the leak alone empty the full cistern?$q$,array[$q$12 h$q$,$q$18 h$q$,$q$15 h$q$,$q$20 h$q$],3,$q$Leak = 1/6 − 1/10 = 1/15; empties in 15 h.$q$);
select public._seed_arith_q($q$Pipes and Cisterns$q$,'medium',$q$A pipe fills a tank in 12 hours; a waste pipe at the bottom empties the full tank in 20 hours. If both are open, how long to fill the empty tank?$q$,array[$q$32 h$q$,$q$8 h$q$,$q$30 h$q$,$q$24 h$q$],3,$q$Net = 1/12 − 1/20 = 2/60 = 1/30; time = 30 h.$q$);
select public._seed_arith_q($q$Pipes and Cisterns$q$,'medium',$q$Pipes A and B can fill a tank in 24 and 32 minutes. Both are opened; after some time A is turned off and the tank fills in 18 minutes total. After how many minutes was A turned off?$q$,array[$q$8 min$q$,$q$10 min$q$,$q$6 min$q$,$q$9 min$q$],1,$q$Let A off after t: t(1/24+1/32)+(18−t)(1/32)=1 ⇒ t=8 (A closed).$q$);
select public._seed_arith_q($q$Pipes and Cisterns$q$,'medium',$q$A tank has a leak that can empty it in 30 hours. An inlet pipe admitting water fills it in 20 hours. With both open, in how many hours is the empty tank filled?$q$,array[$q$50 h$q$,$q$60 h$q$,$q$10 h$q$,$q$12 h$q$],2,$q$Net = 1/20 − 1/30 = 1/60; time = 60 h.$q$);
select public._seed_arith_q($q$Pipes and Cisterns$q$,'medium',$q$A pipe can fill a tank in 15 hours. Due to a leak, it takes 20 hours to fill. If the tank is full, in how many hours will the leak empty it?$q$,array[$q$45 h$q$,$q$60 h$q$,$q$30 h$q$,$q$35 h$q$],2,$q$Leak = 1/15 − 1/20 = 1/60; empties in 60 h.$q$);
select public._seed_arith_q($q$Pipes and Cisterns$q$,'medium',$q$A cistern can be filled by a tap in 4 hours and emptied by another in 9 hours. If both taps are opened together, in how many hours will the empty cistern be filled?$q$,array[$q$36/5 h$q$,$q$36/13 h$q$,$q$13/36 h$q$,$q$36 h$q$],1,$q$Net = 1/4 − 1/9 = 5/36; time = 36/5 = 7.2 h.$q$);
select public._seed_arith_q($q$Pipes and Cisterns$q$,'medium',$q$A pipe fills a cistern in 3 hours. Due to a leak it now takes 3.5 hours. How long will the leak take to empty the full cistern?$q$,array[$q$18 h$q$,$q$21 h$q$,$q$24 h$q$,$q$10.5 h$q$],2,$q$Leak = 1/3 − 1/3.5 = 1/3 − 2/7 = 1/21; empties in 21 h.$q$);
select public._seed_arith_q($q$Pipes and Cisterns$q$,'medium',$q$Two pipes A and B fill a tank in 20 and 30 minutes respectively. Both are opened together but B is closed after 10 minutes. What is the total time to fill the tank?$q$,array[$q$12 min$q$,$q$13 1/3 min$q$,$q$15 min$q$,$q$14 min$q$],2,$q$10 min both: 10(1/20+1/30)=5/6. Remaining 1/6 by A alone: (1/6)/(1/20)=10/3 min. Total = 10 + 10/3 = 40/3 = 13 1/3 min.$q$);
select public._seed_arith_q($q$Pipes and Cisterns$q$,'medium',$q$Two pipes fill a tank in 15 and 20 hours respectively. Both are opened together, but after 4 hours the first pipe is closed. In how many more hours will the second pipe fill the rest?$q$,array[$q$10 h$q$,$q$10 2/3 h$q$,$q$8 h$q$,$q$12 h$q$],1,$q$In 4h: 4(1/15+1/20)=7/15. Remaining 8/15 by second (1/20): (8/15)/(1/20)=32/3 = 10 2/3 h.$q$);
select public._seed_arith_q($q$Pipes and Cisterns$q$,'hard',$q$Pipes A and B fill a tank in 10 and 15 hours. Both are opened together and after 4 hours A is closed. How many more hours will B take to fill the remaining tank?$q$,array[$q$4 h$q$,$q$5 h$q$,$q$6 h$q$,$q$3 h$q$],2,$q$In 4h: 4(1/10+1/15)=4×1/6=2/3. Remaining 1/3 ÷ 1/15 = 5 h.$q$);
select public._seed_arith_q($q$Pipes and Cisterns$q$,'hard',$q$Three pipes A, B and C fill a tank in 6, 8 and (as an outlet) empty it in 12 hours. If all three are opened together, how long to fill the tank?$q$,array[$q$24/5 h$q$,$q$5 h$q$,$q$6 h$q$,$q$4 h$q$],1,$q$Net = 1/6 + 1/8 − 1/12 = 5/24; time = 24/5 = 4.8 h.$q$);
select public._seed_arith_q($q$Pipes and Cisterns$q$,'hard',$q$A tank is filled by three pipes in 10, 20 and 30 minutes respectively. All are opened together but the third acts as an outlet (emptying). In what time is the tank filled?$q$,array[$q$60/7 min$q$,$q$12 min$q$,$q$10 min$q$,$q$8 min$q$],1,$q$Net = 1/10 + 1/20 − 1/30 = 7/60; time = 60/7 min.$q$);
select public._seed_arith_q($q$Pipes and Cisterns$q$,'hard',$q$Pipe A can fill a tank in 8 hours and pipe B in 12 hours. A is opened first and after 2 hours B is also opened. In how much total time is the tank filled?$q$,array[$q$6.2 h$q$,$q$6 h$q$,$q$5.6 h$q$,$q$6.5 h$q$],3,$q$A alone 2h = 1/4. Remaining 3/4 by both (1/8+1/12=5/24): (3/4)/(5/24)=3.6 h. Total 5.6 h.$q$);
select public._seed_arith_q($q$Pipes and Cisterns$q$,'hard',$q$Two fill pipes take 20 and 30 minutes; an outlet empties the full tank in 40 minutes. All three open on an empty tank — in what time is it filled?$q$,array[$q$120/7 min$q$,$q$120/13 min$q$,$q$17 min$q$,$q$15 min$q$],2,$q$Net = 1/20 + 1/30 − 1/40 = 13/120; time = 120/13 min.$q$);
select public._seed_arith_q($q$Pipes and Cisterns$q$,'hard',$q$Three pipes fill a tank in 12, 15 and 20 minutes. All opened together — in what time is the tank filled?$q$,array[$q$5 min$q$,$q$6 min$q$,$q$4 min$q$,$q$7 min$q$],1,$q$1/12+1/15+1/20 = 5+4+3/60 = 12/60 = 1/5; time = 5 min.$q$);
select public._seed_arith_q($q$Pipes and Cisterns$q$,'hard',$q$Two pipes A and B fill a tank in 6 and 4 hours respectively. They are opened alternately for 1 hour each, starting with A. In how many hours will the tank be full?$q$,array[$q$4 h$q$,$q$4.5 h$q$,$q$5 h$q$,$q$5.5 h$q$],3,$q$Per 2-h cycle: 1/6+1/4=5/12. After 4h=5/6. 5th hour (A): 5/6+1/6=1. Full in 5 h.$q$);
select public._seed_arith_q($q$Pipes and Cisterns$q$,'hard',$q$Pipes A and B fill a tank in 12 and 16 minutes respectively. Both are opened together; after 3 minutes B is closed. How much longer will A take to fill the rest?$q$,array[$q$7.25 min$q$,$q$6.75 min$q$,$q$5.5 min$q$,$q$8 min$q$],2,$q$In 3 min: 3(1/12+1/16)=7/16. Remaining 9/16 by A (1/12): (9/16)/(1/12)=6.75 min.$q$);
select public._seed_arith_q($q$Pipes and Cisterns$q$,'hard',$q$Pipe A fills a tank in 15 hours and pipe B empties it in 20 hours. Both are opened on an empty tank; after 5 hours B is closed. In how much more time will A fill the remaining tank?$q$,array[$q$11.25 h$q$,$q$13.75 h$q$,$q$12 h$q$,$q$10 h$q$],2,$q$5h net (1/15−1/20=1/60): 1/12 filled. Remaining 11/12 by A (1/15): (11/12)/(1/15)=13.75 h.$q$);
select public._seed_arith_q($q$Pipes and Cisterns$q$,'very_hard',$q$A cistern has two inlet pipes filling in 12 and 15 hours and an outlet emptying the full cistern in 10 hours. All three are opened together on an empty cistern. In how many hours will it be filled?$q$,array[$q$20 h$q$,$q$18 h$q$,$q$24 h$q$,$q$15 h$q$],1,$q$Net = 1/12 + 1/15 − 1/10 = 5+4−6/60 = 3/60 = 1/20; time = 20 h.$q$);
select public._seed_arith_q($q$Pipes and Cisterns$q$,'very_hard',$q$A tank of 2400 litres has an inlet at 90 L/min and an outlet at 60 L/min. Starting empty with both open, how long to fill the tank?$q$,array[$q$80 min$q$,$q$60 min$q$,$q$120 min$q$,$q$40 min$q$],1,$q$Net = 90 − 60 = 30 L/min; 2400/30 = 80 min.$q$);
select public._seed_arith_q($q$Pipes and Cisterns$q$,'very_hard',$q$A tank is 3/4 full. Pipe A fills the full tank in 12 min and pipe B empties the full tank in 8 min. Both are opened. In how many minutes will the tank be empty?$q$,array[$q$18 min$q$,$q$20 min$q$,$q$24 min$q$,$q$16 min$q$],1,$q$Net empty rate = 1/8 − 1/12 = 1/24. 3/4 ÷ 1/24 = 18 min.$q$);
select public._seed_arith_q($q$Pipes and Cisterns$q$,'very_hard',$q$An outlet empties a full tank in 30 minutes. An inlet admitting 4 L/min is opened and now the full tank empties in 45 minutes. Find the capacity of the tank.$q$,array[$q$360 L$q$,$q$540 L$q$,$q$480 L$q$,$q$240 L$q$],1,$q$Let cap C. Outlet rate = C/30. With inlet: C/45 = C/30 − 4 ⇒ 4 = C(1/30−1/45)=C/90 ⇒ C=360 L.$q$);
select public._seed_arith_q($q$Pipes and Cisterns$q$,'very_hard',$q$Two pipes A and B can fill a tank in 24 and 32 minutes. Both are opened together, and B is turned off after some time so that the tank is full in 18 minutes. After how many minutes was B turned off?$q$,array[$q$8 min$q$,$q$10 min$q$,$q$6 min$q$,$q$12 min$q$],1,$q$Let B off after t: t(1/24+1/32)+(18−t)(1/24)=1 ⇒ t=8 min.$q$);
select public._seed_arith_q($q$Pipes and Cisterns$q$,'very_hard',$q$A tank has three pipes: A fills in 30 min, B fills in 45 min, C empties in 36 min. They are opened in order A, then B (after 5 min), then C (after another 4 min) and left on. Ignoring C, find the time for A and B together to fill it.$q$,array[$q$18 min$q$,$q$20 min$q$,$q$24 min$q$,$q$15 min$q$],1,$q$A+B = 1/30 + 1/45 = 3+2/90 = 5/90 = 1/18; time = 18 min.$q$);
select public._seed_arith_q($q$Pipes and Cisterns$q$,'very_hard',$q$A leak can empty a full cistern in 20 hours. An inlet admits 6 litres/min and, when both are open, the full cistern empties in 24 hours. Find the capacity of the cistern (in litres).$q$,array[$q$43200 L$q$,$q$36000 L$q$,$q$28800 L$q$,$q$51840 L$q$],1,$q$Inlet/hr = 360 L. Leak = C/20. With inlet: C/24 = C/20 − 360 ⇒ 360 = C(1/20−1/24)=C/120 ⇒ C=43200 L.$q$);
select public._seed_arith_q($q$Pipes and Cisterns$q$,'very_hard',$q$Pipe A fills a tank in 20 h, pipe B in 30 h; outlet C empties it in 40 h. All three opened together on an empty tank. In how many hours is it filled?$q$,array[$q$120/7 h$q$,$q$24 h$q$,$q$20 h$q$,$q$15 h$q$],1,$q$Net = 1/20 + 1/30 − 1/40 = 6+4−3/120 = 7/120; time = 120/7 h.$q$);
select public._seed_arith_q($q$Pipes and Cisterns$q$,'very_hard',$q$Pipes A and B fill a tank in 15 and 20 minutes; outlet C empties it in 10 minutes. A and B are opened for 5 minutes, then C is also opened. What is the total time to fill the tank?$q$,array[$q$28 min$q$,$q$30 min$q$,$q$25 min$q$,$q$32 min$q$],2,$q$5 min A+B: 5(1/15+1/20)=7/12. Remaining 5/12 with all three (net 1/15+1/20−1/10=1/60): 25 min. Total = 5+25 = 30 min.$q$);

drop function public._seed_arith_q(text,text,text,text[],int,text);
