-- ============================================================================
-- 057_arith_time_and_work.sql
-- Question-bank seed: Arithmetic chapter "Time and Work" -- 39 single-answer MCQs
-- from ACTUAL previous-year papers (bank PO/Clerk, SSC, ICET, IT placement) via
-- IndiaBix, PrepInsta, Testbook, Adda247, Oliveboard, CareerPower, Examveda, 2IIM,
-- GeeksforGeeks, Sawaal. Exam-grade floor; answers independently recomputed & each
-- correct option re-derived; 4 distinct-valued options, one correct; each carries a
-- worked explanation. Depends on 023. Reuses idempotent _seed_arith_q. Safe to re-run.
-- Together rates, alternate days, pairwise triads, wages, men-women-boys systems.
-- ============================================================================

create or replace function public._seed_arith_q(p_chapter text, p_difficulty text, p_stem text, p_opts text[], p_correct int, p_explanation text) returns void language plpgsql as $$
declare v_subj uuid; v_chap uuid; v_qid uuid; i int;
begin
  select id into v_subj from public.subject where lower(name)='arithmetic' limit 1;
  if v_subj is null then raise exception 'Arithmetic subject not found (run 023 first)'; end if;
  select id into v_chap from public.chapter where subject_id=v_subj and lower(name)=lower(p_chapter) limit 1;
  if v_chap is null then raise exception 'Chapter % not found', p_chapter; end if;
  if exists (select 1 from public.question where chapter_id=v_chap and stem=p_stem) then return; end if;
  insert into public.question (subject_id, chapter_id, kind, difficulty, answer_type, stem, explanation)
  values (v_subj, v_chap, 'standard', p_difficulty, 'single', p_stem, p_explanation) returning id into v_qid;
  for i in 1..array_length(p_opts,1) loop
    insert into public.question_option (question_id, label, is_correct, position) values (v_qid, p_opts[i], i=p_correct, i-1);
  end loop;
end; $$;

-- Time and Work (39 questions)
select public._seed_arith_q($q$Time and Work$q$,'easy',$q$A can complete a piece of work in 10 days and B can complete it in 15 days. Working together, in how many days will they finish the work?$q$,array[$q$6 days$q$,$q$5 days$q$,$q$12 days$q$,$q$8 days$q$],1,$q$1/(1/10+1/15)=1/(1/6)=6 days.$q$);
select public._seed_arith_q($q$Time and Work$q$,'easy',$q$A can do a piece of work in 20 days. He works for 5 days and then stops. What fraction of the work is left?$q$,array[$q$1/4$q$,$q$1/2$q$,$q$3/4$q$,$q$2/3$q$],3,$q$Done=5/20=1/4; left=1-1/4=3/4.$q$);
select public._seed_arith_q($q$Time and Work$q$,'easy',$q$A can build a wall in 20 days and B in 30 days. If they work together, how long will they take?$q$,array[$q$10 days$q$,$q$15 days$q$,$q$12 days$q$,$q$25 days$q$],3,$q$1/(1/20+1/30)=1/(5/60)=12 days.$q$);
select public._seed_arith_q($q$Time and Work$q$,'easy',$q$Pipe/worker A finishes a job in 24 days and B in 6 days. Working together, how many days do they take?$q$,array[$q$4.8 days$q$,$q$5 days$q$,$q$4 days$q$,$q$6 days$q$],1,$q$1/(1/24+1/6)=1/(5/24)=24/5=4.8 days.$q$);
select public._seed_arith_q($q$Time and Work$q$,'easy',$q$A does a task in 12 days and C in 24 days. Working together, how many days will A and C take?$q$,array[$q$9 days$q$,$q$8 days$q$,$q$6 days$q$,$q$10 days$q$],2,$q$1/(1/12+1/24)=1/(3/24)=8 days.$q$);
select public._seed_arith_q($q$Time and Work$q$,'easy',$q$A can do one-third of a work in 5 days. In how many days can A do the whole work?$q$,array[$q$10 days$q$,$q$15 days$q$,$q$20 days$q$,$q$12 days$q$],2,$q$1/3 in 5 days => full = 5×3 = 15 days.$q$);
select public._seed_arith_q($q$Time and Work$q$,'easy',$q$A can finish a work in 18 days. If he works for 12 days and then leaves, what fraction of the work has he completed?$q$,array[$q$1/3$q$,$q$2/3$q$,$q$3/4$q$,$q$1/2$q$],2,$q$Fraction done = 12/18 = 2/3.$q$);
select public._seed_arith_q($q$Time and Work$q$,'easy',$q$A can complete a work in 40 days and B in 60 days. Working together, how long will they take?$q$,array[$q$20 days$q$,$q$24 days$q$,$q$30 days$q$,$q$25 days$q$],2,$q$1/(1/40+1/60)=1/(5/120)=24 days.$q$);
select public._seed_arith_q($q$Time and Work$q$,'easy',$q$A completes 2/5 of a work in 10 days. How many days does A need for the whole work?$q$,array[$q$20 days$q$,$q$30 days$q$,$q$25 days$q$,$q$24 days$q$],3,$q$10 days = 2/5 => whole = 10×(5/2) = 25 days.$q$);
select public._seed_arith_q($q$Time and Work$q$,'easy',$q$A can do a work in 9 days and B in 18 days. Working together, in how many days will the work be done?$q$,array[$q$6 days$q$,$q$7 days$q$,$q$9 days$q$,$q$5 days$q$],1,$q$1/(1/9+1/18)=1/(3/18)=6 days.$q$);
select public._seed_arith_q($q$Time and Work$q$,'medium',$q$A can do a work in 15 days and B in 10 days. They start together, but A leaves after 3 days. How many total days does the work take to complete?$q$,array[$q$8 days$q$,$q$9 days$q$,$q$7 days$q$,$q$10 days$q$],1,$q$3 days work=3(1/15+1/10)=1/2; remaining 1/2 by B alone=(1/2)/(1/10)=5; total=3+5=8.$q$);
select public._seed_arith_q($q$Time and Work$q$,'medium',$q$A is twice as efficient as B. Working together they finish a work in 18 days. In how many days can A alone finish the work?$q$,array[$q$27 days$q$,$q$36 days$q$,$q$24 days$q$,$q$54 days$q$],1,$q$Let B=1/54/day (rate b). a=2b; 3b=1/18=>b=1/54; A=2/54=1/27=>27 days.$q$);
select public._seed_arith_q($q$Time and Work$q$,'medium',$q$A can do a job in 6 days and B in 8 days. They complete it together and are paid Rs. 7000, divided in the ratio of work done. What is A's share?$q$,array[$q$Rs. 3000$q$,$q$Rs. 4000$q$,$q$Rs. 3500$q$,$q$Rs. 4500$q$],2,$q$Work ratio = rates 1/6:1/8 = 4:3; A=7000×4/7=Rs.4000.$q$);
select public._seed_arith_q($q$Time and Work$q$,'medium',$q$A can do a work in 20 days and B in 30 days. They work together for 5 days, then A leaves and B finishes the rest. What is the total time taken?$q$,array[$q$20 days$q$,$q$22.5 days$q$,$q$25 days$q$,$q$21 days$q$],2,$q$5 days=5(1/20+1/30)=5/12 done; remaining 7/12 by B=(7/12)/(1/30)=17.5; total=5+17.5=22.5.$q$);
select public._seed_arith_q($q$Time and Work$q$,'medium',$q$A is three times as efficient as B and takes 60 days less than B to complete a work. In how many days can they finish it working together?$q$,array[$q$20 days$q$,$q$22.5 days$q$,$q$30 days$q$,$q$24 days$q$],2,$q$B=90, A=30 (90-30=60). Together=1/(1/30+1/90)=1/(4/90)=22.5 days.$q$);
select public._seed_arith_q($q$Time and Work$q$,'medium',$q$A can do a work in 16 days and B in 24 days. They finish it together and share wages of Rs. 5000 in the ratio of work done. What is B's share?$q$,array[$q$Rs. 3000$q$,$q$Rs. 2000$q$,$q$Rs. 2500$q$,$q$Rs. 1800$q$],2,$q$Rates 1/16:1/24=3:2; B=5000×2/5=Rs.2000.$q$);
select public._seed_arith_q($q$Time and Work$q$,'medium',$q$The efficiencies of A and B are in the ratio 3:2. Together they complete a work in 12 days. In how many days can B alone complete it?$q$,array[$q$20 days$q$,$q$30 days$q$,$q$36 days$q$,$q$24 days$q$],2,$q$3k+2k=1/12=>k=1/60; B=2k=1/30=>30 days.$q$);
select public._seed_arith_q($q$Time and Work$q$,'medium',$q$A can do a work in 30 days and B in 20 days. They complete it together and are paid Rs. 5000 in the ratio of work done. What is A's share?$q$,array[$q$Rs. 2000$q$,$q$Rs. 3000$q$,$q$Rs. 2500$q$,$q$Rs. 1500$q$],1,$q$Rates 1/30:1/20=2:3; A=5000×2/5=Rs.2000.$q$);
select public._seed_arith_q($q$Time and Work$q$,'medium',$q$A is twice as good a workman as B. Together they finish a piece of work in 14 days. In how many days can B alone do the work?$q$,array[$q$21 days$q$,$q$28 days$q$,$q$42 days$q$,$q$35 days$q$],3,$q$A=2B; 2b+b=1/14=>b=1/42=>B alone=42 days.$q$);
select public._seed_arith_q($q$Time and Work$q$,'hard',$q$A and B together can do a work in 12 days, B and C in 15 days, and C and A in 20 days. In how many days can all three together finish it?$q$,array[$q$10 days$q$,$q$12 days$q$,$q$8 days$q$,$q$15 days$q$],1,$q$2(A+B+C)=1/12+1/15+1/20=1/5 => A+B+C=1/10 => 10 days.$q$);
select public._seed_arith_q($q$Time and Work$q$,'hard',$q$A and B together can do a work in 12 days, B and C in 15 days, and C and A in 20 days. In how many days can A alone finish it?$q$,array[$q$30 days$q$,$q$24 days$q$,$q$20 days$q$,$q$60 days$q$],1,$q$A+B+C=1/10; A=(A+B+C)-(B+C)=1/10-1/15=1/30 => 30 days.$q$);
select public._seed_arith_q($q$Time and Work$q$,'hard',$q$A and B together can complete a work in 10 days, B and C in 15 days, and C and A in 12 days. In how many days can all three together complete it?$q$,array[$q$6 days$q$,$q$8 days$q$,$q$10 days$q$,$q$12 days$q$],2,$q$2(A+B+C)=1/10+1/15+1/12=1/4 => A+B+C=1/8 => 8 days.$q$);
select public._seed_arith_q($q$Time and Work$q$,'hard',$q$A can do a work in 6 days and B in 12 days. They work on alternate days, A starting first. In how many days is the work completed?$q$,array[$q$7 days$q$,$q$8 days$q$,$q$9 days$q$,$q$8.5 days$q$],2,$q$2-day cycle=1/6+1/12=1/4; 4 cycles=8 days=1 complete work. Total 8 days.$q$);
select public._seed_arith_q($q$Time and Work$q$,'hard',$q$A can do a work in 20 days and B in 30 days. They work on alternate days with A beginning. In how many days will the work be finished?$q$,array[$q$24 days$q$,$q$25 days$q$,$q$23 days$q$,$q$26 days$q$],1,$q$2-day cycle=1/20+1/30=1/12; 12 cycles=24 days give exactly 1. Total 24 days.$q$);
select public._seed_arith_q($q$Time and Work$q$,'hard',$q$A can do a work in 12 days and B in 18 days. A works alone for 3 days, then B joins him. In how many total days is the work completed?$q$,array[$q$8.4 days$q$,$q$9 days$q$,$q$7.5 days$q$,$q$8 days$q$],1,$q$A 3 days=3/12=1/4; remaining 3/4 together (5/36/day)=(3/4)/(5/36)=5.4; total=3+5.4=8.4.$q$);
select public._seed_arith_q($q$Time and Work$q$,'hard',$q$A and B together can do a work in 10 days, B and C in 12 days, and A, B and C together in 8 days. In how many days can C alone finish it?$q$,array[$q$30 days$q$,$q$40 days$q$,$q$24 days$q$,$q$20 days$q$],2,$q$C=(A+B+C)-(A+B)=1/8-1/10=1/40 => 40 days.$q$);
select public._seed_arith_q($q$Time and Work$q$,'hard',$q$A, B and C together finish a work in 4 days. A alone takes 12 days and B alone takes 18 days. In how many days can C alone do it?$q$,array[$q$8 days$q$,$q$9 days$q$,$q$10 days$q$,$q$6 days$q$],2,$q$C=1/4-1/12-1/18=(9-3-2)/36=4/36=1/9 => 9 days.$q$);
select public._seed_arith_q($q$Time and Work$q$,'hard',$q$A can do a work in 10 days and B in 15 days. They begin together, but B leaves 5 days before the work is completed. What is the total time taken?$q$,array[$q$7 days$q$,$q$8 days$q$,$q$9 days$q$,$q$7.5 days$q$],2,$q$Let total=T; A works T, B works T-5: T/10+(T-5)/15=1 => 3T+2T-10=30 => T=8.$q$);
select public._seed_arith_q($q$Time and Work$q$,'hard',$q$A, B and C work in rotation on consecutive days in the order A, B, C (A on day 1). A alone finishes in 12 days, B in 15 days, C in 20 days. In how many days is the work completed?$q$,array[$q$15 days$q$,$q$16 days$q$,$q$14 days$q$,$q$18 days$q$],1,$q$3-day cycle=1/12+1/15+1/20=1/5; 5 cycles=15 days give exactly 1. Total 15 days.$q$);
select public._seed_arith_q($q$Time and Work$q$,'very_hard',$q$3 men and 4 women can complete a work in 10 days, while 4 men and 3 women can complete it in 8 days. In how many days can 1 man alone complete the work?$q$,array[$q$35 days$q$,$q$28 days$q$,$q$40 days$q$,$q$30 days$q$],1,$q$30m+40w=1, 32m+24w=1 => m=1/35, w=1/280. 1 man = 35 days.$q$);
select public._seed_arith_q($q$Time and Work$q$,'very_hard',$q$6 men can do a work in 10 days, and 12 women can do the same work in 10 days. In how many days can 8 men and 4 women together do it?$q$,array[$q$5 days$q$,$q$6 days$q$,$q$8 days$q$,$q$7 days$q$],2,$q$1 man=1/60/day, 1 woman=1/120/day; 8m+4w=8/60+4/120=1/6/day => 6 days.$q$);
select public._seed_arith_q($q$Time and Work$q$,'very_hard',$q$A completes 3/4 of a work in 12 days, then B joins him and together they finish the remaining work in 3 more days. In how many days can B alone do the whole work?$q$,array[$q$36 days$q$,$q$48 days$q$,$q$40 days$q$,$q$54 days$q$],2,$q$A rate=(3/4)/12=1/16; remaining 1/4 in 3 days: 3(1/16+b)=1/4 => b=1/12-1/16=1/48 => 48 days.$q$);
select public._seed_arith_q($q$Time and Work$q$,'very_hard',$q$A can do a work in 20 days and B in 30 days. A starts and works 5 days, then leaves; B works the next 5 days, after which A rejoins and both work together till the work is done. What is the total time taken?$q$,array[$q$17 days$q$,$q$18 days$q$,$q$16 days$q$,$q$19 days$q$],1,$q$5(1/20)+5(1/30)=1/4+1/6=5/12 done; remaining 7/12 together(1/12/day)=7 days; total=5+5+7=17.$q$);
select public._seed_arith_q($q$Time and Work$q$,'very_hard',$q$6 men and 8 boys can do a work in 10 days, while 8 men and 6 boys can do it in 8 days. In how many days can 10 men do the same work?$q$,array[$q$7 days$q$,$q$8 days$q$,$q$6 days$q$,$q$9 days$q$],1,$q$60m+80b=1, 64m+48b=1 => m=1/70; 10 men rate=10/70=1/7/day => 7 days.$q$);
select public._seed_arith_q($q$Time and Work$q$,'very_hard',$q$10 men can complete a work in 20 days. They start the work, and after 6 days, 10 more men join them. In how many total days is the work finished?$q$,array[$q$12 days$q$,$q$13 days$q$,$q$14 days$q$,$q$15 days$q$],2,$q$Total=200 man-days; 6 days×10=60 done; remaining 140 by 20 men=7 days; total=6+7=13.$q$);
select public._seed_arith_q($q$Time and Work$q$,'very_hard',$q$12 men can do a work in 20 days, and 15 women can do the same work in 20 days. In how many days can 8 men and 10 women together do it?$q$,array[$q$12 days$q$,$q$15 days$q$,$q$10 days$q$,$q$18 days$q$],2,$q$man=1/240/day, woman=1/300/day; 8m+10w=1/30+1/30=1/15/day => 15 days.$q$);
select public._seed_arith_q($q$Time and Work$q$,'very_hard',$q$The efficiencies of A, B and C are in the ratio 1:2:3. C alone can finish a work in 10 days. In how many days can all three together finish it?$q$,array[$q$6 days$q$,$q$5 days$q$,$q$4 days$q$,$q$8 days$q$],2,$q$C rate(eff3)=1/10 => eff1=1/30; A=1/30,B=1/15,C=1/10; sum=6/30=1/5 => 5 days.$q$);
select public._seed_arith_q($q$Time and Work$q$,'very_hard',$q$A certain number of men can do a work in 25 days. If there were 10 men fewer, it would take 5 days more. How many men were there originally?$q$,array[$q$50$q$,$q$60$q$,$q$55$q$,$q$45$q$],2,$q$M×25=(M-10)×30 => 25M=30M-300 => 5M=300 => M=60.$q$);
select public._seed_arith_q($q$Time and Work$q$,'very_hard',$q$2 men and 4 boys can do a work in 12 days, while 4 men and 2 boys can do it in 10 days. In how many days can 1 man alone complete the work?$q$,array[$q$360/7 days ≈ 51.4$q$,$q$36 days$q$,$q$45 days$q$,$q$40 days$q$],1,$q$24m+48b=1, 40m+20b=1 => m=7/360; 1 man = 360/7 ≈ 51.4 days.$q$);

drop function public._seed_arith_q(text,text,text,text[],int,text);
