-- ============================================================================
-- 059_arith_boats_and_streams.sql
-- Question-bank seed: Arithmetic chapter "Boats and Streams" -- 36 single-answer MCQs
-- from ACTUAL previous-year papers (bank PO/Clerk, SSC, ICET, IT placement) via
-- IndiaBix, PrepInsta, Testbook, Adda247, Oliveboard, CareerPower, Examveda, 2IIM,
-- GeeksforGeeks, Sawaal. Exam-grade floor; answers independently recomputed & each
-- correct option re-derived; 4 distinct-valued options, one correct; each carries a
-- worked explanation. Depends on 023. Reuses idempotent _seed_arith_q. Safe to re-run.
-- Down/up speed, still/stream from speeds, round-trip time, up:down time ratios.
-- ============================================================================

create or replace function public._seed_arith_q(p_chapter text, p_difficulty text, p_stem text, p_opts text[], p_correct int, p_explanation text) returns void language plpgsql as $$
declare v_subj uuid; v_chap uuid; v_qid uuid; i int;
begin
  select id into v_subj from public.subject where lower(name)='arithmetic' limit 1;
  if v_subj is null then raise exception 'Arithmetic subject not found (run 023 first)'; end if;
  select id into v_chap from public.chapter where subject_id=v_subj and lower(name)=lower(p_chapter) limit 1;
  if v_chap is null then raise exception 'Chapter % not found', p_chapter; end if;
  if exists (select 1 from public.question where chapter_id=v_chap and stem=p_stem) then return; end if;
  insert into public.question (subject_id, chapter_id, kind, difficulty, answer_type, stem, explanation)
  values (v_subj, v_chap, 'standard', p_difficulty, 'single', p_stem, p_explanation) returning id into v_qid;
  for i in 1..array_length(p_opts,1) loop
    insert into public.question_option (question_id, label, is_correct, position) values (v_qid, p_opts[i], i=p_correct, i-1);
  end loop;
end; $$;

-- Boats and Streams (36 questions)
select public._seed_arith_q($q$Boats and Streams$q$,'easy',$q$A boat's speed in still water is 15 km/h and the speed of the stream is 3 km/h. Find its downstream speed.$q$,array[$q$12 km/h$q$,$q$18 km/h$q$,$q$21 km/h$q$,$q$9 km/h$q$],2,$q$Downstream = 15+3 = 18 km/h.$q$);
select public._seed_arith_q($q$Boats and Streams$q$,'easy',$q$The speed of a boat in still water is 12 km/h and the stream flows at 4 km/h. Find the upstream speed.$q$,array[$q$16 km/h$q$,$q$8 km/h$q$,$q$6 km/h$q$,$q$10 km/h$q$],2,$q$Upstream = 12-4 = 8 km/h.$q$);
select public._seed_arith_q($q$Boats and Streams$q$,'easy',$q$A boat goes downstream at 22 km/h and upstream at 14 km/h. Find the speed of the boat in still water.$q$,array[$q$4 km/h$q$,$q$36 km/h$q$,$q$18 km/h$q$,$q$8 km/h$q$],3,$q$Still water = (22+14)/2 = 18 km/h.$q$);
select public._seed_arith_q($q$Boats and Streams$q$,'easy',$q$A boat travels downstream at 20 km/h and upstream at 12 km/h. Find the speed of the stream.$q$,array[$q$16 km/h$q$,$q$6 km/h$q$,$q$4 km/h$q$,$q$8 km/h$q$],3,$q$Stream = (20-12)/2 = 4 km/h.$q$);
select public._seed_arith_q($q$Boats and Streams$q$,'easy',$q$A man rows at 8 km/h in still water. If the river flows at 2 km/h, what are his downstream and upstream speeds?$q$,array[$q$10 and 6 km/h$q$,$q$6 and 10 km/h$q$,$q$10 and 4 km/h$q$,$q$12 and 6 km/h$q$],1,$q$Down=8+2=10; Up=8-2=6 km/h.$q$);
select public._seed_arith_q($q$Boats and Streams$q$,'easy',$q$Downstream speed of a boat is 15 km/h and upstream speed is 9 km/h. Find both the still-water speed and the stream speed.$q$,array[$q$12 and 3 km/h$q$,$q$3 and 12 km/h$q$,$q$12 and 6 km/h$q$,$q$24 and 6 km/h$q$],1,$q$Still=(15+9)/2=12; Stream=(15-9)/2=3.$q$);
select public._seed_arith_q($q$Boats and Streams$q$,'easy',$q$A boat can go 5 km/h in still water. The stream speed is 1 km/h. Find the downstream speed.$q$,array[$q$4 km/h$q$,$q$5 km/h$q$,$q$6 km/h$q$,$q$7 km/h$q$],3,$q$Down=5+1=6 km/h.$q$);
select public._seed_arith_q($q$Boats and Streams$q$,'easy',$q$A boat moves downstream at 24 km/h and upstream at 16 km/h. Find the speed of the current.$q$,array[$q$20 km/h$q$,$q$8 km/h$q$,$q$4 km/h$q$,$q$40 km/h$q$],3,$q$Current=(24-16)/2=4 km/h.$q$);
select public._seed_arith_q($q$Boats and Streams$q$,'easy',$q$The still-water speed of a boat is 10 km/h and the current is 2.5 km/h. Find the upstream speed.$q$,array[$q$12.5 km/h$q$,$q$7.5 km/h$q$,$q$5 km/h$q$,$q$8.5 km/h$q$],2,$q$Up=10-2.5=7.5 km/h.$q$);
select public._seed_arith_q($q$Boats and Streams$q$,'medium',$q$A boat covers 36 km downstream in 3 hours. If the stream flows at 2 km/h, find the boat's speed in still water.$q$,array[$q$10 km/h$q$,$q$12 km/h$q$,$q$14 km/h$q$,$q$9 km/h$q$],1,$q$Down speed=36/3=12; still=12-2=10 km/h.$q$);
select public._seed_arith_q($q$Boats and Streams$q$,'medium',$q$A boat goes 40 km upstream in 5 hours. If the boat's still-water speed is 11 km/h, find the stream speed.$q$,array[$q$2 km/h$q$,$q$3 km/h$q$,$q$4 km/h$q$,$q$5 km/h$q$],2,$q$Up speed=40/5=8; stream=11-8=3 km/h.$q$);
select public._seed_arith_q($q$Boats and Streams$q$,'medium',$q$A boat travels 60 km downstream in 4 hours and the stream speed is 3 km/h. How long will it take to travel 45 km upstream?$q$,array[$q$4 hours$q$,$q$5 hours$q$,$q$6 hours$q$,$q$3 hours$q$],2,$q$Down=60/4=15; still=15-3=12; up=12-3=9; time=45/9=5 h.$q$);
select public._seed_arith_q($q$Boats and Streams$q$,'medium',$q$A man rows 15 km downstream in 1.5 hours. The stream flows at 2 km/h. Find his still-water speed.$q$,array[$q$8 km/h$q$,$q$10 km/h$q$,$q$12 km/h$q$,$q$7 km/h$q$],1,$q$Down=15/1.5=10; still=10-2=8 km/h.$q$);
select public._seed_arith_q($q$Boats and Streams$q$,'medium',$q$A boat can travel 30 km upstream in 6 hours. The speed of the current is 1 km/h. Find the time to cover 42 km downstream.$q$,array[$q$5 hours$q$,$q$6 hours$q$,$q$7 hours$q$,$q$8 hours$q$],2,$q$Up=30/6=5; still=5+1=6; down=6+1=7; time=42/7=6 h.$q$);
select public._seed_arith_q($q$Boats and Streams$q$,'medium',$q$A boat covers 24 km downstream in 2 hours and returns the same 24 km upstream in 3 hours. Find its speed in still water.$q$,array[$q$10 km/h$q$,$q$12 km/h$q$,$q$5 km/h$q$,$q$2 km/h$q$],1,$q$Down=12, Up=8; still=(12+8)/2=10 km/h.$q$);
select public._seed_arith_q($q$Boats and Streams$q$,'medium',$q$A boat goes 21 km downstream in 1 hour 45 minutes. If the current is 3 km/h, find the boat's still-water speed.$q$,array[$q$9 km/h$q$,$q$12 km/h$q$,$q$15 km/h$q$,$q$6 km/h$q$],1,$q$1h45m=1.75h; down=21/1.75=12; still=12-3=9 km/h.$q$);
select public._seed_arith_q($q$Boats and Streams$q$,'medium',$q$A boat travels 32 km upstream in 4 hours and 32 km downstream in 2 hours. Find the speed of the stream.$q$,array[$q$8 km/h$q$,$q$4 km/h$q$,$q$2 km/h$q$,$q$12 km/h$q$],2,$q$Up=8, Down=16; stream=(16-8)/2=4 km/h.$q$);
select public._seed_arith_q($q$Boats and Streams$q$,'medium',$q$A boat's downstream speed is 18 km/h. It covers a certain distance downstream in 2 hours. If the current is 4 km/h, how long to cover the same distance upstream?$q$,array[$q$3.6 hours$q$,$q$2 hours$q$,$q$4 hours$q$,$q$5 hours$q$],1,$q$Distance=18*2=36; still=18-4=14; up=14-4=10; time=36/10=3.6 h.$q$);
select public._seed_arith_q($q$Boats and Streams$q$,'hard',$q$A man can row 8 km/h in still water. When the river runs at 4 km/h, it takes him 3 hours to row to a place and back. How far is the place?$q$,array[$q$9 km$q$,$q$10 km$q$,$q$6 km$q$,$q$12 km$q$],1,$q$Down=12, Up=4. d/12+d/4=3 -> d(4/12)=3 -> d=9 km.$q$);
select public._seed_arith_q($q$Boats and Streams$q$,'hard',$q$A man rows to a place 48 km away and comes back in 14 hours. He finds he can row 4 km downstream in the same time as 3 km upstream. Find the stream speed.$q$,array[$q$1 km/h$q$,$q$2 km/h$q$,$q$3 km/h$q$,$q$4 km/h$q$],1,$q$down:up rate=4:3, so up=3k,down=4k. 48/4k+48/3k=14 -> 28/k=14 -> k=2; down=8,up=6; stream=(8-6)/2=1.$q$);
select public._seed_arith_q($q$Boats and Streams$q$,'hard',$q$A boat covers 24 km downstream and 16 km upstream in 6 hours; and 36 km downstream and 40 km upstream in 13 hours. Find the still-water speed.$q$,array[$q$6 km/h$q$,$q$8 km/h$q$,$q$4 km/h$q$,$q$10 km/h$q$],2,$q$Let x=1/down, y=1/up: 24x+16y=6 and 36x+40y=13 → down=12, up=4. Still water=(12+4)/2=8 km/h.$q$);
select public._seed_arith_q($q$Boats and Streams$q$,'hard',$q$A person can row 9 km/h in still water. In a river flowing at 3 km/h it takes him 6 hours to row to a place and back. How far is the place?$q$,array[$q$24 km$q$,$q$30 km$q$,$q$36 km$q$,$q$20 km$q$],1,$q$Down=12, Up=6. d/12+d/6=6 -> 3d/12=6 -> d=24 km.$q$);
select public._seed_arith_q($q$Boats and Streams$q$,'hard',$q$A boat can row 8 km/h in still water. In a stream of 2 km/h it takes 8 hours to go to a place and return. Find the one-way distance.$q$,array[$q$30 km$q$,$q$28 km$q$,$q$24 km$q$,$q$36 km$q$],1,$q$Down=10, Up=6. d/10+d/6=8 -> d(8/30)=8 -> d=30 km.$q$);
select public._seed_arith_q($q$Boats and Streams$q$,'hard',$q$A man rows 750 metres in 675 seconds against the stream and returns in 7.5 minutes. Find his rowing speed in still water (km/h).$q$,array[$q$4 km/h$q$,$q$5 km/h$q$,$q$6 km/h$q$,$q$3 km/h$q$],2,$q$Up=750/675 m/s=4 km/h; Down=750/450 m/s=6 km/h; still=(4+6)/2=5 km/h.$q$);
select public._seed_arith_q($q$Boats and Streams$q$,'hard',$q$A boat takes 90 minutes more to go 36 km upstream than to go the same distance downstream. If the still-water speed is 10 km/h, find the stream speed.$q$,array[$q$2 km/h$q$,$q$3 km/h$q$,$q$4 km/h$q$,$q$5 km/h$q$],1,$q$36/(10-s)-36/(10+s)=1.5. s=2: 36/8-36/12=4.5-3=1.5 -> s=2.$q$);
select public._seed_arith_q($q$Boats and Streams$q$,'hard',$q$A boat rows 5 km downstream in the same time it rows 3 km upstream. If the stream speed is 2 km/h, find the boat's still-water speed.$q$,array[$q$8 km/h$q$,$q$6 km/h$q$,$q$10 km/h$q$,$q$5 km/h$q$],1,$q$down:up=5:3 -> (b+2)/(b-2)=5/3 -> 3b+6=5b-10 -> b=8 km/h.$q$);
select public._seed_arith_q($q$Boats and Streams$q$,'hard',$q$A boat covers 20 km downstream in 2 hours and 20 km upstream in 5 hours. Find the distance the boat can travel downstream in 3 hours.$q$,array[$q$30 km$q$,$q$24 km$q$,$q$36 km$q$,$q$20 km$q$],1,$q$Down=20/2=10 km/h; distance in 3h = 10*3 = 30 km.$q$);
select public._seed_arith_q($q$Boats and Streams$q$,'very_hard',$q$A boat takes twice as long to go a distance upstream as downstream. If the boat's still-water speed is 12 km/h, find the stream speed.$q$,array[$q$3 km/h$q$,$q$4 km/h$q$,$q$6 km/h$q$,$q$2 km/h$q$],2,$q$time up=2*time down -> up speed=down/2 -> (b-s)=(b+s)/2 -> 2b-2s=b+s -> b=3s -> s=4 km/h.$q$);
select public._seed_arith_q($q$Boats and Streams$q$,'very_hard',$q$The ratio of a boat's upstream to downstream time for the same distance is 3:1. If the stream speed is 4 km/h, find the boat's still-water speed.$q$,array[$q$6 km/h$q$,$q$8 km/h$q$,$q$10 km/h$q$,$q$12 km/h$q$],2,$q$time up:down=3:1 -> down:up speed=3:1 -> (b+s)=3(b-s) -> b+4=3b-12 -> b=8 km/h.$q$);
select public._seed_arith_q($q$Boats and Streams$q$,'very_hard',$q$A boat's still-water speed is 15 km/h. The time taken upstream is thrice the time downstream for equal distances. Find the current speed.$q$,array[$q$5 km/h$q$,$q$6 km/h$q$,$q$7.5 km/h$q$,$q$10 km/h$q$],3,$q$down:up speed=3:1 -> (15+s)=3(15-s) -> 15+s=45-3s -> 4s=30 -> s=7.5 km/h.$q$);
select public._seed_arith_q($q$Boats and Streams$q$,'very_hard',$q$In one hour a boat goes 11 km downstream and 5 km upstream. Find the speed of the boat in still water.$q$,array[$q$3 km/h$q$,$q$8 km/h$q$,$q$6 km/h$q$,$q$16 km/h$q$],2,$q$Down=11, Up=5; still=(11+5)/2=8 km/h.$q$);
select public._seed_arith_q($q$Boats and Streams$q$,'very_hard',$q$A boat rows a certain distance downstream in 4 hours and returns the same distance in 6 hours. If the stream speed is 2 km/h, find the distance.$q$,array[$q$48 km$q$,$q$24 km$q$,$q$36 km$q$,$q$60 km$q$],1,$q$down=d/4, up=d/6; stream=(d/4-d/6)/2=2 -> d(1/12)=4 -> d=48 km.$q$);
select public._seed_arith_q($q$Boats and Streams$q$,'very_hard',$q$A steamer covers the distance between two ports in 5 hours downstream and 6 hours upstream. If the stream flows at 2 km/h, find the still-water speed.$q$,array[$q$22 km/h$q$,$q$24 km/h$q$,$q$20 km/h$q$,$q$18 km/h$q$],1,$q$d=5(b+2)=6(b-2) -> 5b+10=6b-12 -> b=22 km/h.$q$);
select public._seed_arith_q($q$Boats and Streams$q$,'very_hard',$q$A man rows 30 km downstream in 6 hours and 18 km upstream in 6 hours. Find the speed of the current.$q$,array[$q$1 km/h$q$,$q$2 km/h$q$,$q$3 km/h$q$,$q$4 km/h$q$],1,$q$Down=30/6=5, Up=18/6=3; current=(5-3)/2=1 km/h.$q$);
select public._seed_arith_q($q$Boats and Streams$q$,'very_hard',$q$A boat takes 4 hours more to travel 60 km upstream than to travel the same 60 km downstream. If the still-water speed is 8 km/h, find the stream speed.$q$,array[$q$2 km/h$q$,$q$3 km/h$q$,$q$4 km/h$q$,$q$5 km/h$q$],1,$q$60/(8−s)−60/(8+s)=4 → 120s=4(64−s²) → s²+30s−64=0 → s=2 km/h. (Check: 60/6−60/10=10−6=4.)$q$);
select public._seed_arith_q($q$Boats and Streams$q$,'very_hard',$q$A boat travels 30 km downstream and 30 km upstream in 8 hours; on another trip it travels 40 km downstream and 24 km upstream also in 8 hours. Find the speed of the stream.$q$,array[$q$2 km/h$q$,$q$3 km/h$q$,$q$4 km/h$q$,$q$1 km/h$q$],1,$q$Let 1/down=x,1/up=y: 30x+30y=8, 40x+24y=8 -> down=10,up=6; stream=(10-6)/2=2 km/h.$q$);

drop function public._seed_arith_q(text,text,text,text[],int,text);
