-- ============================================================================
-- 060_arith_problems_on_trains.sql
-- Question-bank seed: Arithmetic chapter "Problems on Trains" -- 36 single-answer MCQs
-- from ACTUAL previous-year papers (bank PO/Clerk, SSC, ICET, IT placement) via
-- IndiaBix, PrepInsta, Testbook, Adda247, Oliveboard, CareerPower, Examveda, 2IIM,
-- GeeksforGeeks, Sawaal. Exam-grade floor; answers independently recomputed & each
-- correct option re-derived; 4 distinct-valued options, one correct; each carries a
-- worked explanation. Depends on 023. Reuses idempotent _seed_arith_q. Safe to re-run.
-- Crossing pole/platform, two trains (same/opposite), train vs walker, length/speed.
-- ============================================================================

create or replace function public._seed_arith_q(p_chapter text, p_difficulty text, p_stem text, p_opts text[], p_correct int, p_explanation text) returns void language plpgsql as $$
declare v_subj uuid; v_chap uuid; v_qid uuid; i int;
begin
  select id into v_subj from public.subject where lower(name)='arithmetic' limit 1;
  if v_subj is null then raise exception 'Arithmetic subject not found (run 023 first)'; end if;
  select id into v_chap from public.chapter where subject_id=v_subj and lower(name)=lower(p_chapter) limit 1;
  if v_chap is null then raise exception 'Chapter % not found', p_chapter; end if;
  if exists (select 1 from public.question where chapter_id=v_chap and stem=p_stem) then return; end if;
  insert into public.question (subject_id, chapter_id, kind, difficulty, answer_type, stem, explanation)
  values (v_subj, v_chap, 'standard', p_difficulty, 'single', p_stem, p_explanation) returning id into v_qid;
  for i in 1..array_length(p_opts,1) loop
    insert into public.question_option (question_id, label, is_correct, position) values (v_qid, p_opts[i], i=p_correct, i-1);
  end loop;
end; $$;

-- Problems on Trains (36 questions)
select public._seed_arith_q($q$Problems on Trains$q$,'easy',$q$A train running at 60 km/hr crosses a pole in 9 seconds. What is the length of the train?$q$,array[$q$120 metres$q$,$q$150 metres$q$,$q$180 metres$q$,$q$324 metres$q$],2,$q$Speed = 60 x 5/18 = 50/3 m/s. Length = speed x time = (50/3) x 9 = 150 m.$q$);
select public._seed_arith_q($q$Problems on Trains$q$,'easy',$q$A 150 m long train is running at 90 km/hr. How long will it take to cross an electric pole?$q$,array[$q$5 sec$q$,$q$6 sec$q$,$q$7.5 sec$q$,$q$9 sec$q$],2,$q$90 km/hr = 90 x 5/18 = 25 m/s. Time = 150 / 25 = 6 sec.$q$);
select public._seed_arith_q($q$Problems on Trains$q$,'easy',$q$Convert a speed of 72 km/hr into metres per second.$q$,array[$q$18 m/s$q$,$q$20 m/s$q$,$q$25 m/s$q$,$q$28 m/s$q$],2,$q$72 x 5/18 = 20 m/s.$q$);
select public._seed_arith_q($q$Problems on Trains$q$,'easy',$q$A train 100 m long moving at 30 km/hr crosses a signal post. Find the time taken.$q$,array[$q$10 sec$q$,$q$12 sec$q$,$q$15 sec$q$,$q$18 sec$q$],2,$q$30 km/hr = 30 x 5/18 = 25/3 m/s. Time = 100 / (25/3) = 12 sec.$q$);
select public._seed_arith_q($q$Problems on Trains$q$,'easy',$q$Express 45 km/hr in metres per second.$q$,array[$q$11.5 m/s$q$,$q$12.5 m/s$q$,$q$13.5 m/s$q$,$q$15 m/s$q$],2,$q$45 x 5/18 = 12.5 m/s.$q$);
select public._seed_arith_q($q$Problems on Trains$q$,'easy',$q$A train 500 m long crosses a pole in 20 seconds. Find its speed in km/hr.$q$,array[$q$72 km/hr$q$,$q$80 km/hr$q$,$q$90 km/hr$q$,$q$100 km/hr$q$],3,$q$Speed = 500/20 = 25 m/s = 25 x 18/5 = 90 km/hr.$q$);
select public._seed_arith_q($q$Problems on Trains$q$,'easy',$q$A train 120 m long is running at 54 km/hr. In what time will it pass a stationary observer on the platform?$q$,array[$q$6 sec$q$,$q$7 sec$q$,$q$8 sec$q$,$q$10 sec$q$],3,$q$54 km/hr = 15 m/s. Time = 120 / 15 = 8 sec.$q$);
select public._seed_arith_q($q$Problems on Trains$q$,'easy',$q$A train travelling at 72 km/hr crosses a telegraph post in 10 seconds. Find the length of the train.$q$,array[$q$180 m$q$,$q$200 m$q$,$q$220 m$q$,$q$250 m$q$],2,$q$72 km/hr = 20 m/s. Length = 20 x 10 = 200 m.$q$);
select public._seed_arith_q($q$Problems on Trains$q$,'easy',$q$A 250 m long train runs at 36 km/hr. Find the time it takes to cross a pole.$q$,array[$q$20 sec$q$,$q$22 sec$q$,$q$25 sec$q$,$q$30 sec$q$],3,$q$36 km/hr = 10 m/s. Time = 250 / 10 = 25 sec.$q$);
select public._seed_arith_q($q$Problems on Trains$q$,'medium',$q$A train 240 m long, running at 90 km/hr, crosses a platform 360 m long. How long does it take?$q$,array[$q$20 sec$q$,$q$24 sec$q$,$q$28 sec$q$,$q$30 sec$q$],2,$q$90 km/hr = 25 m/s. Total distance = 240 + 360 = 600 m. Time = 600 / 25 = 24 sec.$q$);
select public._seed_arith_q($q$Problems on Trains$q$,'medium',$q$A train 130 m long is running at 45 km/hr. How long will it take to cross a bridge 230 m long?$q$,array[$q$24 sec$q$,$q$26.4 sec$q$,$q$28.8 sec$q$,$q$30 sec$q$],3,$q$45 km/hr = 12.5 m/s. Total = 130 + 230 = 360 m. Time = 360 / 12.5 = 28.8 sec.$q$);
select public._seed_arith_q($q$Problems on Trains$q$,'medium',$q$A train 300 m long crosses a platform 200 m long in 20 seconds. Find the speed of the train in km/hr.$q$,array[$q$72 km/hr$q$,$q$80 km/hr$q$,$q$90 km/hr$q$,$q$96 km/hr$q$],3,$q$Total = 300 + 200 = 500 m. Speed = 500/20 = 25 m/s = 90 km/hr.$q$);
select public._seed_arith_q($q$Problems on Trains$q$,'medium',$q$A 250 m long train crosses a bridge 500 m long in 30 seconds. What is its speed?$q$,array[$q$80 km/hr$q$,$q$85 km/hr$q$,$q$90 km/hr$q$,$q$95 km/hr$q$],3,$q$Total = 250 + 500 = 750 m. Speed = 750/30 = 25 m/s = 90 km/hr.$q$);
select public._seed_arith_q($q$Problems on Trains$q$,'medium',$q$A train 110 m long running at 60 km/hr crosses a platform in 12 seconds. Find the length of the platform.$q$,array[$q$80 m$q$,$q$90 m$q$,$q$100 m$q$,$q$120 m$q$],2,$q$60 km/hr = 50/3 m/s. Total = (50/3) x 12 = 200 m. Platform = 200 - 110 = 90 m.$q$);
select public._seed_arith_q($q$Problems on Trains$q$,'medium',$q$A train 120 m long crosses a platform 120 m long in 20 seconds. Find the speed of the train.$q$,array[$q$36 km/hr$q$,$q$40 km/hr$q$,$q$43.2 km/hr$q$,$q$48 km/hr$q$],3,$q$Total = 240 m. Speed = 240/20 = 12 m/s = 12 x 18/5 = 43.2 km/hr.$q$);
select public._seed_arith_q($q$Problems on Trains$q$,'medium',$q$A train 150 m long is moving at 72 km/hr. How long will it take to pass a platform 250 m long?$q$,array[$q$18 sec$q$,$q$20 sec$q$,$q$22 sec$q$,$q$25 sec$q$],2,$q$72 km/hr = 20 m/s. Total = 400 m. Time = 400/20 = 20 sec.$q$);
select public._seed_arith_q($q$Problems on Trains$q$,'medium',$q$A train 100 m long crosses a platform 150 m long in 15 seconds. Find its speed in km/hr.$q$,array[$q$54 km/hr$q$,$q$60 km/hr$q$,$q$66 km/hr$q$,$q$72 km/hr$q$],2,$q$Total = 250 m. Speed = 250/15 = 50/3 m/s = (50/3) x 18/5 = 60 km/hr.$q$);
select public._seed_arith_q($q$Problems on Trains$q$,'medium',$q$A train running at 54 km/hr crosses a platform 264 m long in 20 seconds. Find the length of the train.$q$,array[$q$30 m$q$,$q$36 m$q$,$q$40 m$q$,$q$45 m$q$],2,$q$54 km/hr = 15 m/s. Total = 15 x 20 = 300 m. Train length = 300 - 264 = 36 m.$q$);
select public._seed_arith_q($q$Problems on Trains$q$,'hard',$q$Two trains 140 m and 160 m long run in opposite directions at 60 km/hr and 40 km/hr. In what time will they cross each other?$q$,array[$q$9.8 sec$q$,$q$10.2 sec$q$,$q$10.8 sec$q$,$q$11.4 sec$q$],3,$q$Relative speed = 60 + 40 = 100 km/hr = 250/9 m/s. Total = 300 m. Time = 300 / (250/9) = 10.8 sec.$q$);
select public._seed_arith_q($q$Problems on Trains$q$,'hard',$q$Two trains 210 m and 190 m long run in the same direction at 72 km/hr and 54 km/hr. How long does the faster train take to cross the slower one?$q$,array[$q$72 sec$q$,$q$76 sec$q$,$q$80 sec$q$,$q$84 sec$q$],3,$q$Relative speed = 72 - 54 = 18 km/hr = 5 m/s. Total = 400 m. Time = 400/5 = 80 sec.$q$);
select public._seed_arith_q($q$Problems on Trains$q$,'hard',$q$A train 150 m long running at 90 km/hr crosses a man walking at 6 km/hr in the opposite direction. Find the time taken.$q$,array[$q$5.0 sec$q$,$q$5.625 sec$q$,$q$6.0 sec$q$,$q$6.25 sec$q$],2,$q$Relative speed = 90 + 6 = 96 km/hr = 80/3 m/s. Time = 150 / (80/3) = 5.625 sec.$q$);
select public._seed_arith_q($q$Problems on Trains$q$,'hard',$q$A train 120 m long moving at 45 km/hr passes a man walking at 9 km/hr in the same direction. Find the time taken.$q$,array[$q$10 sec$q$,$q$11 sec$q$,$q$12 sec$q$,$q$14 sec$q$],3,$q$Relative speed = 45 - 9 = 36 km/hr = 10 m/s. Time = 120 / 10 = 12 sec.$q$);
select public._seed_arith_q($q$Problems on Trains$q$,'hard',$q$Two trains, each 120 m long, run in opposite directions at 40 km/hr and 50 km/hr. In what time do they completely cross each other?$q$,array[$q$8.4 sec$q$,$q$9.0 sec$q$,$q$9.6 sec$q$,$q$10.2 sec$q$],3,$q$Relative speed = 90 km/hr = 25 m/s. Total = 240 m. Time = 240/25 = 9.6 sec.$q$);
select public._seed_arith_q($q$Problems on Trains$q$,'hard',$q$A train 130 m long moving at 68 km/hr passes a man running at 5 km/hr in the same direction as the train. Find the time taken.$q$,array[$q$6 sec$q$,$q$7.43 sec$q$,$q$8 sec$q$,$q$9 sec$q$],2,$q$Relative speed = 68 - 5 = 63 km/hr = 17.5 m/s. Time = 130 / 17.5 = 7.43 sec.$q$);
select public._seed_arith_q($q$Problems on Trains$q$,'hard',$q$Two trains run in the same direction at 40 km/hr and 22 km/hr. The faster train, 150 m long, crosses the slower train in 60 seconds. Find the length of the slower train.$q$,array[$q$120 m$q$,$q$140 m$q$,$q$150 m$q$,$q$160 m$q$],3,$q$Relative speed = 18 km/hr = 5 m/s. Total = 5 x 60 = 300 m. Slower train = 300 - 150 = 150 m.$q$);
select public._seed_arith_q($q$Problems on Trains$q$,'hard',$q$A train 100 m long passes a man running at 4 km/hr in the same direction in 4.5 seconds. Find the speed of the train.$q$,array[$q$80 km/hr$q$,$q$82 km/hr$q$,$q$84 km/hr$q$,$q$86 km/hr$q$],3,$q$Relative speed = 100/4.5 = 200/9 m/s = 80 km/hr. Train speed = 80 + 4 = 84 km/hr.$q$);
select public._seed_arith_q($q$Problems on Trains$q$,'hard',$q$A train 240 m long running at 90 km/hr overtakes a man running at 6 km/hr in the same direction. How long does it take to pass him?$q$,array[$q$9.6 sec$q$,$q$10.0 sec$q$,$q$10.29 sec$q$,$q$11.0 sec$q$],3,$q$Relative speed = 90 - 6 = 84 km/hr = 70/3 m/s. Time = 240 / (70/3) = 10.29 sec.$q$);
select public._seed_arith_q($q$Problems on Trains$q$,'very_hard',$q$Two trains of equal length 100 m each pass each other in 10 seconds when moving in opposite directions and in 30 seconds when moving in the same direction. Find the speed of the faster train.$q$,array[$q$36 km/hr$q$,$q$42 km/hr$q$,$q$48 km/hr$q$,$q$54 km/hr$q$],3,$q$Opposite: (200)/(u+v)=10 -> u+v=20. Same: (200)/(u-v)=30 -> u-v=20/3. u=(20+20/3)/2=40/3 m/s = 48 km/hr.$q$);
select public._seed_arith_q($q$Problems on Trains$q$,'very_hard',$q$A train passes a platform 162 m long in 18 seconds and a man standing on the platform in 9 seconds. Find the length of the train.$q$,array[$q$150 m$q$,$q$162 m$q$,$q$180 m$q$,$q$200 m$q$],2,$q$Let speed v m/s. Man: L = 9v. Platform: L + 162 = 18v. So 9v = 162 -> v = 18 m/s, L = 162 m.$q$);
select public._seed_arith_q($q$Problems on Trains$q$,'very_hard',$q$A train crosses a platform 100 m long in 25 seconds and a pole in 15 seconds. Find the length of the train.$q$,array[$q$120 m$q$,$q$135 m$q$,$q$150 m$q$,$q$165 m$q$],3,$q$Pole: L = 15v. Platform: L + 100 = 25v -> 10v = 100 -> v = 10 m/s, L = 150 m.$q$);
select public._seed_arith_q($q$Problems on Trains$q$,'very_hard',$q$Two trains 137 m and 163 m long run towards each other on parallel tracks at equal speeds and cross in 10 seconds. Find the speed of each train.$q$,array[$q$48 km/hr$q$,$q$50 km/hr$q$,$q$54 km/hr$q$,$q$60 km/hr$q$],3,$q$Total = 300 m. Combined speed = 300/10 = 30 m/s = 2u -> u = 15 m/s = 54 km/hr each.$q$);
select public._seed_arith_q($q$Problems on Trains$q$,'very_hard',$q$A train overtakes two persons walking in the same direction as the train at 2 km/hr and 4 km/hr, passing them in 9 s and 10 s respectively. Find the speed of the train.$q$,array[$q$20 km/hr$q$,$q$22 km/hr$q$,$q$24 km/hr$q$,$q$25 km/hr$q$],2,$q$v(m/s)=10u2-9u1 with u1=2x5/18, u2=4x5/18 -> v = 55/9 m/s = 22 km/hr.$q$);
select public._seed_arith_q($q$Problems on Trains$q$,'very_hard',$q$A train crosses a platform 200 m long in 45 seconds and another platform 300 m long in 60 seconds. Find the length of the train.$q$,array[$q$90 m$q$,$q$100 m$q$,$q$110 m$q$,$q$120 m$q$],2,$q$(L+200)/45 = (L+300)/60 -> 60(L+200)=45(L+300) -> 15L=1500 -> L=100 m.$q$);
select public._seed_arith_q($q$Problems on Trains$q$,'very_hard',$q$Two trains, 100 m each, cross each other in 8 seconds when running in opposite directions and in 24 seconds in the same direction. Find the speed of the faster train.$q$,array[$q$48 km/hr$q$,$q$54 km/hr$q$,$q$60 km/hr$q$,$q$66 km/hr$q$],3,$q$Opposite: 200/(u+v)=8 -> u+v=25. Same: 200/(u-v)=24 -> u-v=25/3. u=(25+25/3)/2=50/3 m/s=60 km/hr.$q$);
select public._seed_arith_q($q$Problems on Trains$q$,'very_hard',$q$Two trains, each 100 m long, move in the same direction at 40 km/hr and 20 km/hr. How long will the faster train take to completely pass the slower train?$q$,array[$q$30 sec$q$,$q$33 sec$q$,$q$36 sec$q$,$q$40 sec$q$],3,$q$Relative speed = 20 km/hr = 50/9 m/s. Total = 200 m. Time = 200/(50/9) = 36 sec.$q$);
select public._seed_arith_q($q$Problems on Trains$q$,'very_hard',$q$A train 125 m long passes a man running at 5 km/hr in the same direction as the train in 10 seconds. Find the speed of the train.$q$,array[$q$45 km/hr$q$,$q$48 km/hr$q$,$q$50 km/hr$q$,$q$55 km/hr$q$],3,$q$Relative speed = 125/10 = 12.5 m/s = 45 km/hr. Train speed = 45 + 5 = 50 km/hr.$q$);

drop function public._seed_arith_q(text,text,text,text[],int,text);
