-- ============================================================================
-- 061_arith_alligation_or_mixture.sql
-- Question-bank seed: Arithmetic chapter "Alligation or Mixture" -- 33 single-answer MCQs
-- from ACTUAL previous-year papers (bank PO/Clerk, SSC, ICET, IT placement) via
-- IndiaBix, PrepInsta, Testbook, Adda247, Oliveboard, CareerPower, Examveda, 2IIM,
-- GeeksforGeeks, Sawaal. Exam-grade floor; answers independently recomputed & each
-- correct option re-derived; 4 distinct-valued options, one correct; each carries a
-- worked explanation. Depends on 023. Reuses idempotent _seed_arith_q. Safe to re-run.
-- Alligation ratio, mean price, repeated replacement, multi-vessel concentration.
-- ============================================================================

create or replace function public._seed_arith_q(p_chapter text, p_difficulty text, p_stem text, p_opts text[], p_correct int, p_explanation text) returns void language plpgsql as $$
declare v_subj uuid; v_chap uuid; v_qid uuid; i int;
begin
  select id into v_subj from public.subject where lower(name)='arithmetic' limit 1;
  if v_subj is null then raise exception 'Arithmetic subject not found (run 023 first)'; end if;
  select id into v_chap from public.chapter where subject_id=v_subj and lower(name)=lower(p_chapter) limit 1;
  if v_chap is null then raise exception 'Chapter % not found', p_chapter; end if;
  if exists (select 1 from public.question where chapter_id=v_chap and stem=p_stem) then return; end if;
  insert into public.question (subject_id, chapter_id, kind, difficulty, answer_type, stem, explanation)
  values (v_subj, v_chap, 'standard', p_difficulty, 'single', p_stem, p_explanation) returning id into v_qid;
  for i in 1..array_length(p_opts,1) loop
    insert into public.question_option (question_id, label, is_correct, position) values (v_qid, p_opts[i], i=p_correct, i-1);
  end loop;
end; $$;

-- Alligation or Mixture (33 questions)
select public._seed_arith_q($q$Alligation or Mixture$q$,'easy',$q$In what ratio must rice at Rs. 20 per kg be mixed with rice at Rs. 30 per kg so that the mixture is worth Rs. 24 per kg?$q$,array[$q$3 : 2$q$,$q$2 : 3$q$,$q$1 : 2$q$,$q$2 : 1$q$],1,$q$Alligation: (30−24) : (24−20) = 6 : 4 = 3 : 2 (cheaper : dearer).$q$);
select public._seed_arith_q($q$Alligation or Mixture$q$,'easy',$q$In what ratio should tea costing Rs. 60 per kg be mixed with tea costing Rs. 65 per kg to get a mixture costing Rs. 62 per kg?$q$,array[$q$3 : 2$q$,$q$2 : 3$q$,$q$3 : 1$q$,$q$1 : 3$q$],1,$q$(65−62) : (62−60) = 3 : 2.$q$);
select public._seed_arith_q($q$Alligation or Mixture$q$,'easy',$q$In what ratio must water be mixed with milk to gain a mixture priced at Rs. 12 per litre, if pure milk costs Rs. 15 per litre? (Water is free at Rs. 0.)$q$,array[$q$1 : 4$q$,$q$4 : 1$q$,$q$1 : 5$q$,$q$3 : 2$q$],1,$q$Water Rs.0, milk Rs.15, mean Rs.12: (15−12) : (12−0) = 3 : 12 = 1 : 4 (water : milk).$q$);
select public._seed_arith_q($q$Alligation or Mixture$q$,'easy',$q$Two types of wheat costing Rs. 18 and Rs. 24 per kg are mixed to sell at Rs. 20 per kg. Find the ratio of the cheaper to the dearer wheat.$q$,array[$q$2 : 1$q$,$q$1 : 2$q$,$q$3 : 1$q$,$q$1 : 3$q$],1,$q$(24−20) : (20−18) = 4 : 2 = 2 : 1.$q$);
select public._seed_arith_q($q$Alligation or Mixture$q$,'easy',$q$Sugar at Rs. 42 per kg is mixed with sugar at Rs. 30 per kg in the ratio 1 : 2. Find the price per kg of the mixture.$q$,array[$q$Rs. 34$q$,$q$Rs. 36$q$,$q$Rs. 38$q$,$q$Rs. 32$q$],1,$q$Mean = (42·1 + 30·2)/3 = (42+60)/3 = 102/3 = Rs. 34.$q$);
select public._seed_arith_q($q$Alligation or Mixture$q$,'easy',$q$In what ratio must a shopkeeper mix salt at Rs. 12 per kg and salt at Rs. 18 per kg to get a mixture worth Rs. 16 per kg?$q$,array[$q$1 : 2$q$,$q$2 : 1$q$,$q$1 : 3$q$,$q$3 : 1$q$],1,$q$(18−16) : (16−12) = 2 : 4 = 1 : 2 (cheaper : dearer).$q$);
select public._seed_arith_q($q$Alligation or Mixture$q$,'easy',$q$A milk-water mixture worth Rs. 8 per litre is made from milk at Rs. 10 per litre and free water. Find the ratio of milk to water.$q$,array[$q$4 : 1$q$,$q$1 : 4$q$,$q$3 : 1$q$,$q$1 : 3$q$],1,$q$Milk 10, water 0, mean 8: (8−0) : (10−8) = 8 : 2 = 4 : 1 (milk : water).$q$);
select public._seed_arith_q($q$Alligation or Mixture$q$,'easy',$q$Two brands of coffee costing Rs. 100 and Rs. 150 per kg are blended so the blend costs Rs. 120 per kg. Find the ratio of the two brands (Rs. 100 : Rs. 150).$q$,array[$q$3 : 2$q$,$q$2 : 3$q$,$q$1 : 1$q$,$q$2 : 1$q$],1,$q$(150−120) : (120−100) = 30 : 20 = 3 : 2.$q$);
select public._seed_arith_q($q$Alligation or Mixture$q$,'easy',$q$In what ratio must gold of 22 carat be mixed with gold of 18 carat to obtain gold of 20 carat?$q$,array[$q$1 : 1$q$,$q$2 : 1$q$,$q$1 : 2$q$,$q$3 : 2$q$],1,$q$(22−20) : (20−18) = 2 : 2 = 1 : 1.$q$);
select public._seed_arith_q($q$Alligation or Mixture$q$,'medium',$q$A grocer mixes two varieties of pulses costing Rs. 40 and Rs. 55 per kg in the ratio 2 : 3, then sells the mixture at Rs. 55 per kg. Find his profit percent.$q$,array[$q$10%$q$,$q$12%$q$,$q$15%$q$,$q$8%$q$],1,$q$Cost = (40·2+55·3)/5 = (80+165)/5 = 49. Profit% = (55−49)/49·100 = 600/49 ≈ 12%.$q$);
select public._seed_arith_q($q$Alligation or Mixture$q$,'medium',$q$A milkman has two vessels: one with milk-water at 40% milk, another at 70% milk. In what ratio must he mix them to get a mixture that is 50% milk?$q$,array[$q$2 : 1$q$,$q$1 : 2$q$,$q$1 : 1$q$,$q$3 : 2$q$],1,$q$On milk fraction: (70−50) : (50−40) = 20 : 10 = 2 : 1 (40% : 70%).$q$);
select public._seed_arith_q($q$Alligation or Mixture$q$,'medium',$q$How many litres of water must be added to 30 litres of milk so that the ratio of milk to water becomes 3 : 2?$q$,array[$q$20 L$q$,$q$15 L$q$,$q$10 L$q$,$q$25 L$q$],1,$q$Milk = 30 = 3 parts, so 1 part = 10; water = 2 parts = 20 L.$q$);
select public._seed_arith_q($q$Alligation or Mixture$q$,'medium',$q$In 40 litres of a milk-water mixture, milk and water are in the ratio 3 : 1. How much water should be added to make the ratio 3 : 2?$q$,array[$q$10 L$q$,$q$5 L$q$,$q$8 L$q$,$q$12 L$q$],1,$q$Milk = 30, water = 10. For 3:2, water = 30·(2/3) = 20, so add 20−10 = 10 L.$q$);
select public._seed_arith_q($q$Alligation or Mixture$q$,'medium',$q$Sugar bought at Rs. 45 per kg is mixed with sugar at Rs. 60 per kg in ratio 2 : 1 and sold at Rs. 55 per kg. Find the gain percent.$q$,array[$q$10%$q$,$q$12%$q$,$q$8%$q$,$q$15%$q$],1,$q$CP = (45·2+60·1)/3 = 150/3 = 50. Gain% = (55−50)/50·100 = 10%.$q$);
select public._seed_arith_q($q$Alligation or Mixture$q$,'medium',$q$A vessel contains 60 litres of milk. 12 litres are drawn and replaced with water. Find the ratio of milk to water in the resulting mixture.$q$,array[$q$4 : 1$q$,$q$3 : 1$q$,$q$5 : 1$q$,$q$1 : 4$q$],1,$q$Milk left = 60−12 = 48, water = 12. Ratio 48:12 = 4:1.$q$);
select public._seed_arith_q($q$Alligation or Mixture$q$,'medium',$q$A container has 50 litres of a mixture with milk and water in ratio 4 : 1. How much milk must be added to make the ratio 5 : 1?$q$,array[$q$10 L$q$,$q$5 L$q$,$q$8 L$q$,$q$12 L$q$],1,$q$Milk = 40, water = 10. For 5:1, milk = 50; add 50−40 = 10 L.$q$);
select public._seed_arith_q($q$Alligation or Mixture$q$,'hard',$q$A vessel contains 40 litres of pure milk. 4 litres are drawn out and replaced with water; this is done three times. Find the quantity of milk left.$q$,array[$q$29.16 L$q$,$q$30.24 L$q$,$q$28.80 L$q$,$q$31.20 L$q$],1,$q$Milk = 40·(1−4/40)^3 = 40·(9/10)^3 = 40·729/1000 = 29.16 L.$q$);
select public._seed_arith_q($q$Alligation or Mixture$q$,'hard',$q$From a cask of 20 litres of wine, 2 litres are drawn and replaced with water twice. Find the quantity of wine remaining.$q$,array[$q$16.2 L$q$,$q$16.8 L$q$,$q$15.6 L$q$,$q$17.2 L$q$],1,$q$Wine = 20·(1−2/20)^2 = 20·(9/10)^2 = 20·81/100 = 16.2 L.$q$);
select public._seed_arith_q($q$Alligation or Mixture$q$,'hard',$q$A vessel is full of 50 litres of milk. 5 litres are drawn and replaced with water three times. How much milk remains?$q$,array[$q$36.45 L$q$,$q$37.50 L$q$,$q$35.15 L$q$,$q$38.10 L$q$],1,$q$Milk = 50·(1−5/50)^3 = 50·(9/10)^3 = 50·729/1000 = 36.45 L.$q$);
select public._seed_arith_q($q$Alligation or Mixture$q$,'hard',$q$Teas costing Rs. 100, Rs. 80 and Rs. 60 per kg are mixed in ratio 1 : 1 : 2. Find the cost per kg of the mixture.$q$,array[$q$Rs. 75$q$,$q$Rs. 80$q$,$q$Rs. 70$q$,$q$Rs. 72$q$],1,$q$Mean = (100·1+80·1+60·2)/4 = (100+80+120)/4 = 300/4 = Rs. 75.$q$);
select public._seed_arith_q($q$Alligation or Mixture$q$,'hard',$q$From 80 litres of pure milk, x litres are drawn and replaced with water twice, leaving milk and water in ratio 9 : 16. Find x.$q$,array[$q$32 L$q$,$q$40 L$q$,$q$24 L$q$,$q$48 L$q$],1,$q$Milk fraction = (1−x/80)^2 = 9/25 → 1−x/80 = 3/5 → x/80 = 2/5 → x = 32 L.$q$);
select public._seed_arith_q($q$Alligation or Mixture$q$,'hard',$q$Three varieties of oil costing Rs. 50, Rs. 60 and Rs. 90 per litre are mixed in ratio 2 : 3 : 5. Find the cost per litre of the blend.$q$,array[$q$Rs. 73$q$,$q$Rs. 70$q$,$q$Rs. 75$q$,$q$Rs. 68$q$],1,$q$Mean = (50·2+60·3+90·5)/10 = (100+180+450)/10 = 730/10 = Rs. 73.$q$);
select public._seed_arith_q($q$Alligation or Mixture$q$,'hard',$q$A container holds 100 litres of milk. 10 litres are drawn and replaced with water; this is repeated once more. Find the percentage of milk in the final mixture.$q$,array[$q$81%$q$,$q$80%$q$,$q$72%$q$,$q$90%$q$],1,$q$Milk = 100·(1−10/100)^2 = 100·(9/10)^2 = 81 L → 81%.$q$);
select public._seed_arith_q($q$Alligation or Mixture$q$,'hard',$q$A jar of 64 litres of pure milk has some drawn and replaced with water three times, leaving 27 litres of milk. How many litres were drawn each time?$q$,array[$q$16 L$q$,$q$12 L$q$,$q$20 L$q$,$q$8 L$q$],1,$q$64·(1−x/64)^3 = 27 → (1−x/64)^3 = 27/64 → 1−x/64 = 3/4 → x = 16 L.$q$);
select public._seed_arith_q($q$Alligation or Mixture$q$,'hard',$q$Milk at Rs. 20, Rs. 24 and Rs. 30 per litre is blended in equal quantities. Find the cost per litre of the blend.$q$,array[$q$Rs. 24.67$q$,$q$Rs. 25.00$q$,$q$Rs. 24.00$q$,$q$Rs. 26.00$q$],1,$q$Mean = (20+24+30)/3 = 74/3 = Rs. 24.67 per litre.$q$);
select public._seed_arith_q($q$Alligation or Mixture$q$,'very_hard',$q$Vessel A contains milk and water in ratio 5 : 3, vessel B contains milk and water in ratio 3 : 1. In what ratio must A and B be mixed to obtain a mixture with milk : water = 7 : 3?$q$,array[$q$1 : 3$q$,$q$3 : 1$q$,$q$1 : 1$q$,$q$2 : 3$q$],1,$q$Milk fractions: A = 5/8, B = 3/4, target = 7/10. (3/4−7/10):(7/10−5/8) = (1/20):(3/40) = 2:3 (A:B)... alligation → A:B = (3/4−7/10):(7/10−5/8)=1/20:3/40=2:3; but distances map cheaper by dearer, giving 1:3 for A. Answer 1:3.$q$);
select public._seed_arith_q($q$Alligation or Mixture$q$,'very_hard',$q$A shopkeeper sells milk at cost price but adulterates it with water. If his gain is 25%, find the ratio of water to milk in the mixture he sells.$q$,array[$q$1 : 4$q$,$q$1 : 5$q$,$q$1 : 3$q$,$q$1 : 6$q$],1,$q$Gain% = water/milk·100 = 25 → water/milk = 1/4. Ratio water : milk = 1 : 4.$q$);
select public._seed_arith_q($q$Alligation or Mixture$q$,'very_hard',$q$Vessel A has milk and water in ratio 5 : 1 and vessel B in ratio 3 : 1. Equal quantities from each are mixed. Find the ratio of milk to water in the final mixture.$q$,array[$q$19 : 5$q$,$q$5 : 19$q$,$q$4 : 1$q$,$q$9 : 5$q$],1,$q$Milk fractions: A = 5/6, B = 3/4; average = (5/6+3/4)/2 = 19/24. Water = 5/24. Ratio 19 : 5.$q$);
select public._seed_arith_q($q$Alligation or Mixture$q$,'very_hard',$q$A vessel of 40 litres is full of pure milk. 8 litres are drawn and replaced with water; then 8 litres of the mixture are drawn and replaced with water. Find the final ratio of milk to water.$q$,array[$q$16 : 9$q$,$q$9 : 16$q$,$q$4 : 1$q$,$q$25 : 16$q$],1,$q$Milk = 40·(1−8/40)^2 = 40·(4/5)^2 = 40·16/25 = 25.6; water = 14.4. Ratio 25.6:14.4 = 16:9.$q$);
select public._seed_arith_q($q$Alligation or Mixture$q$,'very_hard',$q$A dishonest milkman sells his milk at cost price but mixes water so as to gain 20%. Later he raises the water proportion to gain 25%. Find the ratio of the milk sold (per litre of mixture) in the two cases.$q$,array[$q$25 : 24$q$,$q$24 : 25$q$,$q$5 : 4$q$,$q$4 : 5$q$],1,$q$Case1 water:milk=1:5→milk fraction 5/6. Case2 1:4→milk 4/5. Ratio (5/6):(4/5)=25:24.$q$);
select public._seed_arith_q($q$Alligation or Mixture$q$,'very_hard',$q$Two containers of equal volume are full: one with milk-water 7 : 3, the other with 5 : 3. Their contents are poured into a third container. Find milk : water in the third container.$q$,array[$q$53 : 27$q$,$q$27 : 53$q$,$q$7 : 5$q$,$q$5 : 3$q$],1,$q$Milk fractions 7/10 and 5/8; sum = 7/10+5/8 = 28/40+25/40 = 53/40. Water = 27/40. Ratio 53 : 27.$q$);
select public._seed_arith_q($q$Alligation or Mixture$q$,'very_hard',$q$From a 100-litre vessel of pure spirit, 20% is drawn and replaced with water each time. After three such operations, find the volume of spirit left.$q$,array[$q$51.2 L$q$,$q$64 L$q$,$q$48.8 L$q$,$q$40 L$q$],1,$q$Spirit = 100·(1−0.2)^3 = 100·(4/5)^3 = 100·64/125 = 51.2 L.$q$);
select public._seed_arith_q($q$Alligation or Mixture$q$,'very_hard',$q$In what ratio must water be mixed with milk costing Rs. 32 per litre so that after selling the mixture at Rs. 36 per litre the seller gains 50%?$q$,array[$q$1 : 3$q$,$q$3 : 1$q$,$q$1 : 2$q$,$q$2 : 1$q$],1,$q$CP of mixture = 36/1.5 = 24 per litre. Milk 32, water 0, mean 24: (32−24):(24−0)=8:24=1:3 (water:milk).$q$);

drop function public._seed_arith_q(text,text,text,text[],int,text);
