-- ============================================================================
-- 066_arith_races_and_games.sql
-- Question-bank seed: Arithmetic chapter "Races and Games of Skill" -- 35 single-answer MCQs
-- from ACTUAL previous-year papers / standard aptitude texts (bank PO/Clerk, SSC,
-- ICET, IT placement). Exam-grade floor; answers independently recomputed & each
-- correct option verified; 4 distinct-valued options, one correct; each carries a
-- worked explanation. Depends on 023. Reuses idempotent _seed_arith_q. Safe to re-run.
-- Beats by distance/time, starts, chained beats, points games, dead-heat scaling.
-- ============================================================================

create or replace function public._seed_arith_q(p_chapter text, p_difficulty text, p_stem text, p_opts text[], p_correct int, p_explanation text) returns void language plpgsql as $$
declare v_subj uuid; v_chap uuid; v_qid uuid; i int;
begin
  select id into v_subj from public.subject where lower(name)='arithmetic' limit 1;
  if v_subj is null then raise exception 'Arithmetic subject not found (run 023 first)'; end if;
  select id into v_chap from public.chapter where subject_id=v_subj and lower(name)=lower(p_chapter) limit 1;
  if v_chap is null then raise exception 'Chapter % not found', p_chapter; end if;
  if exists (select 1 from public.question where chapter_id=v_chap and stem=p_stem) then return; end if;
  insert into public.question (subject_id, chapter_id, kind, difficulty, answer_type, stem, explanation)
  values (v_subj, v_chap, 'standard', p_difficulty, 'single', p_stem, p_explanation) returning id into v_qid;
  for i in 1..array_length(p_opts,1) loop
    insert into public.question_option (question_id, label, is_correct, position) values (v_qid, p_opts[i], i=p_correct, i-1);
  end loop;
end; $$;

-- Races and Games of Skill (35 questions)
select public._seed_arith_q($q$Races and Games of Skill$q$,'easy',$q$In a 100 m race, A beats B by 20 metres. When A has finished the race, how far has B run?$q$,array[$q$70 m$q$,$q$75 m$q$,$q$80 m$q$,$q$85 m$q$],3,$q$A runs 100 m; B is 20 m behind → B has run 100−20 = 80 m.$q$);
select public._seed_arith_q($q$Races and Games of Skill$q$,'easy',$q$In a race, A beats B by 15 seconds. If B takes 90 seconds to finish, how long does A take?$q$,array[$q$72 s$q$,$q$75 s$q$,$q$78 s$q$,$q$70 s$q$],2,$q$A finishes 15 s before B: 90−15 = 75 s.$q$);
select public._seed_arith_q($q$Races and Games of Skill$q$,'easy',$q$'A gives B a start of 25 metres' in a 200 m race means B has to run only:$q$,array[$q$175 m$q$,$q$200 m$q$,$q$150 m$q$,$q$165 m$q$],1,$q$B starts 25 m ahead, so B runs 200−25 = 175 m.$q$);
select public._seed_arith_q($q$Races and Games of Skill$q$,'easy',$q$A runs 100 m in 20 seconds and B in 25 seconds. By how many seconds does A beat B?$q$,array[$q$3 s$q$,$q$4 s$q$,$q$5 s$q$,$q$6 s$q$],3,$q$Both run 100 m; A beats B by the time gap = 25−20 = 5 s.$q$);
select public._seed_arith_q($q$Races and Games of Skill$q$,'easy',$q$In a 100 m race A beats B by 4 metres or 2 seconds. What is B's speed?$q$,array[$q$1.5 m/s$q$,$q$2 m/s$q$,$q$2.5 m/s$q$,$q$3 m/s$q$],2,$q$B covers the last 4 m in 2 s → speed = 4/2 = 2 m/s.$q$);
select public._seed_arith_q($q$Races and Games of Skill$q$,'easy',$q$In a game of 100 points, A can give B 20 points. When A scores 100, B scores:$q$,array[$q$75$q$,$q$80$q$,$q$90$q$,$q$70$q$],2,$q$Giving 20 points means B is 20 behind: 100−20 = 80.$q$);
select public._seed_arith_q($q$Races and Games of Skill$q$,'easy',$q$A runs 200 m in 24 s and B runs 200 m in 30 s. In a 200 m race, by how many metres does A beat B?$q$,array[$q$40 m$q$,$q$45 m$q$,$q$30 m$q$,$q$36 m$q$],1,$q$When A finishes (24 s), B runs 200/30×24 = 160 m; beat = 200−160 = 40 m.$q$);
select public._seed_arith_q($q$Races and Games of Skill$q$,'easy',$q$A runs at 5 m/s and B at 4 m/s over 100 m. When A finishes, how far behind is B?$q$,array[$q$25 m$q$,$q$10 m$q$,$q$15 m$q$,$q$20 m$q$],4,$q$A's time = 100/5 = 20 s; B covers 4×20 = 80 m; behind by 100−80 = 20 m.$q$);
select public._seed_arith_q($q$Races and Games of Skill$q$,'easy',$q$In a 1000 m race A beats B by 40 metres. The ratio of the distances covered by A and B in that time is:$q$,array[$q$24 : 25$q$,$q$25 : 24$q$,$q$5 : 4$q$,$q$4 : 5$q$],2,$q$A runs 1000, B runs 960; ratio 1000:960 = 25:24.$q$);
select public._seed_arith_q($q$Races and Games of Skill$q$,'medium',$q$In a 100 m race A beats B by 10 m and C by 13 m. In a 180 m race, by how many metres will B beat C?$q$,array[$q$5.4 m$q$,$q$6 m$q$,$q$6.5 m$q$,$q$4.8 m$q$],2,$q$B:C = 90:87. In 180 m for B, C runs 180×87/90 = 174; beat = 180−174 = 6 m.$q$);
select public._seed_arith_q($q$Races and Games of Skill$q$,'medium',$q$In a 1 km race A beats B by 28 metres or 7 seconds. A's time over the course is:$q$,array[$q$4 min 8 s$q$,$q$4 min 10 s$q$,$q$3 min 50 s$q$,$q$4 min 3 s$q$],4,$q$B does 28 m in 7 s → 4 m/s → 1000 m in 250 s; A = 250−7 = 243 s = 4 min 3 s.$q$);
select public._seed_arith_q($q$Races and Games of Skill$q$,'medium',$q$A runs 1¾ times as fast as B. If A gives B a start of 84 m, how long must the race be so that both finish together?$q$,array[$q$210 m$q$,$q$168 m$q$,$q$180 m$q$,$q$196 m$q$],4,$q$Speeds A:B = 7:4; A gains 3 m per 7 m run; race = (7/3)×84 = 196 m.$q$);
select public._seed_arith_q($q$Races and Games of Skill$q$,'medium',$q$In a 200 m race A beats B by 35 m or 7 seconds. A's time over the course is:$q$,array[$q$30 s$q$,$q$33 s$q$,$q$35 s$q$,$q$40 s$q$],2,$q$B does 35 m in 7 s → 5 m/s → 200 m in 40 s; A = 40−7 = 33 s.$q$);
select public._seed_arith_q($q$Races and Games of Skill$q$,'medium',$q$In a 300 m race A beats B by 15 m, and B beats C by 20 m. By how many metres does A beat C in the 300 m race?$q$,array[$q$32 m$q$,$q$34 m$q$,$q$36 m$q$,$q$30 m$q$],2,$q$A:B = 20:19, B:C = 15:14. When A runs 300, C runs 300×19/20×14/15 = 266; beat = 34 m.$q$);
select public._seed_arith_q($q$Races and Games of Skill$q$,'medium',$q$A runs 1 km in 3 min 40 s and B in 4 min. By what distance does A beat B in a 1 km race?$q$,array[$q$90 m$q$,$q$100 m$q$,$q$75 m$q$,$q$83.33 m$q$],4,$q$A=220 s, B=240 s. In 220 s B runs 1000/240×220 = 916.67 m; beat = 83.33 m.$q$);
select public._seed_arith_q($q$Races and Games of Skill$q$,'medium',$q$In a game of 80 points, A can give B 5 points and C 15 points. How many points can B give C in a game of 80?$q$,array[$q$12$q$,$q$8$q$,$q$9.33$q$,$q$10.67$q$],4,$q$A:B=80:75, A:C=80:65 → B:C=75:65=15:13. In 80, C=80×13/15=69.33; B gives 10.67.$q$);
select public._seed_arith_q($q$Races and Games of Skill$q$,'medium',$q$A gives B a start of 42 m and still beats him by 2 seconds in a 200 m race. If B runs at 3 m/s, A's time for 200 m is:$q$,array[$q$48.67 s$q$,$q$50.67 s$q$,$q$52.67 s$q$,$q$46.67 s$q$],2,$q$B runs 200−42 = 158 m at 3 m/s = 52.67 s; A = 52.67−2 = 50.67 s.$q$);
select public._seed_arith_q($q$Races and Games of Skill$q$,'medium',$q$A and B run a 500 m race and A wins by 25 m. If A now gives B a start of 25 m over 500 m, the result is:$q$,array[$q$B wins by 1.25 m$q$,$q$Dead heat$q$,$q$A wins by 2.5 m$q$,$q$A wins by 1.25 m$q$],2,$q$A:B = 500:475. With a 25 m start B must run 475 m, which he covers exactly as A runs 500 → dead heat.$q$);
select public._seed_arith_q($q$Races and Games of Skill$q$,'hard',$q$In a 100 m race, A can give B 20 m and C 28 m. In the same 100 m race, how many metres can B give C?$q$,array[$q$10 m$q$,$q$12 m$q$,$q$8 m$q$,$q$9 m$q$],1,$q$B:C = 80:72. When B runs 100, C runs 72/80×100 = 90; B gives 100−90 = 10 m.$q$);
select public._seed_arith_q($q$Races and Games of Skill$q$,'hard',$q$In a game of 100 points, A can give B 20 points and C 28 points. How many points can B give C?$q$,array[$q$9$q$,$q$8$q$,$q$10$q$,$q$12$q$],3,$q$A:B=100:80, A:C=100:72 → B:C=80:72. When B=100, C=90; B gives 10.$q$);
select public._seed_arith_q($q$Races and Games of Skill$q$,'hard',$q$A beats B by 100 m in a 1000 m race and B beats C by 100 m in a 1000 m race. By how many metres does A beat C in a 1000 m race?$q$,array[$q$180 m$q$,$q$190 m$q$,$q$200 m$q$,$q$210 m$q$],2,$q$A:B=B:C=10:9. When A=1000, C=1000×0.9×0.9=810; beat = 190 m.$q$);
select public._seed_arith_q($q$Races and Games of Skill$q$,'hard',$q$In a 100 m race A beats B by 10 m and C by 28 m. If B and C run a 90 m race, by how much does B beat C?$q$,array[$q$16.2 m$q$,$q$18 m$q$,$q$20 m$q$,$q$15 m$q$],2,$q$B:C = 90:72 = 5:4. In 90 m for B, C runs 90×4/5 = 72; beat = 18 m.$q$);
select public._seed_arith_q($q$Races and Games of Skill$q$,'hard',$q$A can give B a start of 20 m and C a start of 39 m in a 400 m race. What start can B give C in the same race?$q$,array[$q$20 m$q$,$q$21 m$q$,$q$18 m$q$,$q$19 m$q$],1,$q$A:B=400:380, A:C=400:361 → B:C=380:361=20:19. In 400, C=380; B gives 20 m.$q$);
select public._seed_arith_q($q$Races and Games of Skill$q$,'hard',$q$In a 1200 m race A beats B by 120 m and A beats C by 156 m. By how many metres does B beat C in the same race?$q$,array[$q$48 m$q$,$q$36 m$q$,$q$40 m$q$,$q$44 m$q$],3,$q$B:C = 1080:1044. When B runs 1200, C runs 1044/1080×1200 = 1160; beat = 40 m.$q$);
select public._seed_arith_q($q$Races and Games of Skill$q$,'hard',$q$A runs 5/4 as fast as B. In a 500 m race, what start can A give B so that both finish together?$q$,array[$q$80 m$q$,$q$90 m$q$,$q$100 m$q$,$q$120 m$q$],3,$q$Speeds 5:4 → in A's time B covers 500×4/5 = 400 m; start = 500−400 = 100 m.$q$);
select public._seed_arith_q($q$Races and Games of Skill$q$,'hard',$q$In a 100 m race A beats B by 10 m and B beats C by 10 m. By how many metres does A beat C?$q$,array[$q$19 m$q$,$q$20 m$q$,$q$21 m$q$,$q$18 m$q$],1,$q$A:B=B:C=10:9. When A=100, C=100×0.9×0.9=81; beat = 19 m.$q$);
select public._seed_arith_q($q$Races and Games of Skill$q$,'hard',$q$In a 200 m race A beats B by 20 m and C by 38 m. How many metres can B give C in a 200 m race?$q$,array[$q$22 m$q$,$q$24 m$q$,$q$18 m$q$,$q$20 m$q$],4,$q$B:C=180:162=10:9. When B=200, C=180; B gives 20 m.$q$);
select public._seed_arith_q($q$Races and Games of Skill$q$,'very_hard',$q$In a game of 100 points, A can give B 20 points and B can give C 25 points. How many points can A give C in a game of 100?$q$,array[$q$45$q$,$q$30$q$,$q$35$q$,$q$40$q$],4,$q$A:B=100:80, B:C=100:75. When A=100, B=80, C=80×75/100=60; A gives 40.$q$);
select public._seed_arith_q($q$Races and Games of Skill$q$,'very_hard',$q$C beats A by 20 m and A beats B by 25 m, each in a 100 m race. By how many metres does C beat B in a 100 m race?$q$,array[$q$38 m$q$,$q$40 m$q$,$q$41 m$q$,$q$45 m$q$],2,$q$C:A=100:80, A:B=100:75. When C=100, A=80, B=80×75/100=60; C beats B by 40 m.$q$);
select public._seed_arith_q($q$Races and Games of Skill$q$,'very_hard',$q$In a 150-point game, A can give B 30 points and C 40 points. In a 150-point game between B and C, the result is:$q$,array[$q$B beats C by 12.5 pts$q$,$q$C beats B by 12.5 pts$q$,$q$B beats C by 15 pts$q$,$q$B beats C by 10 pts$q$],1,$q$A:B=150:120, A:C=150:110 → B:C=120:110=12:11. When B=150, C=137.5; B beats C by 12.5.$q$);
select public._seed_arith_q($q$Races and Games of Skill$q$,'very_hard',$q$A beats B by 10 s, B beats C by 15 s, and A beats C by 20 s over the same course. This data is:$q$,array[$q$Consistent only if speeds are equal$q$,$q$Consistent; A's time is 45 s$q$,$q$Consistent; C's time fixed$q$,$q$Inconsistent, since 10 + 15 ≠ 20$q$],4,$q$Time margins add along the chain: A beats C should be 10+15 = 25 s, but 20 s is given → inconsistent.$q$);
select public._seed_arith_q($q$Races and Games of Skill$q$,'very_hard',$q$In a 100 m race A can give B 10 m and C 20 m. In a 100 m race between B and C where B gives C a 5 m start, the result is:$q$,array[$q$Dead heat$q$,$q$B wins by ~6.1 m$q$,$q$C wins by ~6.1 m$q$,$q$B wins by 5 m$q$],2,$q$B:C=90:80=9:8. With a 5 m start C runs 95 m, but in B's time C covers 100×8/9+5 = 93.9 m < 100 → B wins by ~6.1 m.$q$);
select public._seed_arith_q($q$Races and Games of Skill$q$,'very_hard',$q$In a 400 m race A beats B by 40 m and C by 76 m. How many metres does B beat C in a 400 m race?$q$,array[$q$36 m$q$,$q$40 m$q$,$q$44 m$q$,$q$48 m$q$],2,$q$B:C=360:324=10:9. When B=400, C=360; B beats C by 40 m.$q$);
select public._seed_arith_q($q$Races and Games of Skill$q$,'very_hard',$q$A can run a km in 4 min 54 s and B in 5 min. By what distance does A beat B in a 1 km race (approx)?$q$,array[$q$20 m$q$,$q$24 m$q$,$q$30 m$q$,$q$18 m$q$],1,$q$A=294 s, B=300 s. In 294 s B runs 1000/300×294 = 980 m; beat = 20 m.$q$);
select public._seed_arith_q($q$Races and Games of Skill$q$,'very_hard',$q$In a 100 m race A gives B a start of 4 m and beats him by 1 s; in a 100 m race A gives C a start of 4 m and beats him by 3 s. If A runs 100 m in 20 s, by how much time does B beat C over their own 96 m?$q$,array[$q$3 s$q$,$q$4 s$q$,$q$1 s$q$,$q$2 s$q$],4,$q$When A finishes (20 s) B and C are each at 96 m; B needs 1 s more, C needs 3 s more for the last 4 m, so B beats C by 3−1 = 2 s.$q$);

drop function public._seed_arith_q(text,text,text,text[],int,text);
