-- ============================================================================
-- 074_arith: seed the 'Heights and Distances' Arithmetic chapter of the exam question bank.
-- 36 distinct competitive-exam questions across easy/medium/hard/very_hard,
-- each with 4 options and a worked explanation. Idempotent (skips existing stems).
-- ============================================================================
create or replace function public._seed_arith_q(p_chapter text, p_difficulty text, p_stem text, p_opts text[], p_correct int, p_explanation text) returns void language plpgsql as $fn$
declare v_subj uuid; v_chap uuid; v_qid uuid; i int;
begin
  select id into v_subj from public.subject where lower(name)='arithmetic' limit 1;
  if v_subj is null then raise exception 'Arithmetic subject not found (run 023 first)'; end if;
  select id into v_chap from public.chapter where subject_id=v_subj and lower(name)=lower(p_chapter) limit 1;
  if v_chap is null then raise exception 'Chapter % not found', p_chapter; end if;
  if exists (select 1 from public.question where chapter_id=v_chap and stem=p_stem) then return; end if;
  insert into public.question (subject_id, chapter_id, kind, difficulty, answer_type, stem, explanation)
  values (v_subj, v_chap, 'standard', p_difficulty, 'single', p_stem, p_explanation) returning id into v_qid;
  for i in 1..array_length(p_opts,1) loop
    insert into public.question_option (question_id, label, is_correct, position) values (v_qid, p_opts[i], i=p_correct, i-1);
  end loop;
end; $fn$;

select public._seed_arith_q($q$Heights and Distances$q$, $q$easy$q$, $q$The angle of elevation of the top of a vertical pole from a point 30 m from its base is 30°. Find the height of the pole. (Take √3 = 1.732)$q$, ARRAY[$q$17.32 m$q$,$q$30 m$q$,$q$51.96 m$q$,$q$10 m$q$], 1, $q$h = 30·tan30° = 30/√3 = 17.32 m.$q$);
select public._seed_arith_q($q$Heights and Distances$q$, $q$easy$q$, $q$The angle of elevation of the top of a tower from a point 50 m away on level ground is 60°. What is the height of the tower? (√3 = 1.732)$q$, ARRAY[$q$50 m$q$,$q$28.87 m$q$,$q$100 m$q$,$q$86.6 m$q$], 4, $q$h = 50·tan60° = 50√3 = 86.6 m.$q$);
select public._seed_arith_q($q$Heights and Distances$q$, $q$easy$q$, $q$The top of a tower 60 m high is observed at an angle of elevation of 45° from a point on the ground. How far is the point from the foot of the tower?$q$, ARRAY[$q$60 m$q$,$q$30 m$q$,$q$103.9 m$q$,$q$42.4 m$q$], 1, $q$tan45° = h/d = 1, so d = h = 60 m.$q$);
select public._seed_arith_q($q$Heights and Distances$q$, $q$easy$q$, $q$The angle of elevation of the top of a tower from a point 25 m from its base is 60°. Find its height. (√3 = 1.732)$q$, ARRAY[$q$25 m$q$,$q$43.3 m$q$,$q$14.43 m$q$,$q$50 m$q$], 2, $q$h = 25·tan60° = 25√3 = 43.3 m.$q$);
select public._seed_arith_q($q$Heights and Distances$q$, $q$easy$q$, $q$From a point on the ground the angle of elevation of the top of a tower of height 100 m is 30°. Find the distance of the point from the base of the tower. (√3 = 1.732)$q$, ARRAY[$q$57.7 m$q$,$q$100 m$q$,$q$50 m$q$,$q$173.2 m$q$], 4, $q$d = h/tan30° = 100·√3 = 173.2 m.$q$);
select public._seed_arith_q($q$Heights and Distances$q$, $q$easy$q$, $q$A ladder 10 m long leans against a vertical wall, making an angle of 60° with the ground. How high up the wall does the ladder reach? (√3 = 1.732)$q$, ARRAY[$q$5 m$q$,$q$10 m$q$,$q$8.66 m$q$,$q$17.32 m$q$], 3, $q$height = 10·sin60° = 10×(√3/2) = 8.66 m.$q$);
select public._seed_arith_q($q$Heights and Distances$q$, $q$easy$q$, $q$The angle of elevation of the top of a tower from a point 90 m from its base is 30°. Find the height of the tower. (√3 = 1.732)$q$, ARRAY[$q$51.96 m$q$,$q$155.9 m$q$,$q$90 m$q$,$q$30 m$q$], 1, $q$h = 90·tan30° = 90/√3 = 51.96 m.$q$);
select public._seed_arith_q($q$Heights and Distances$q$, $q$easy$q$, $q$A kite is flying at the end of a taut string 60 m long, making an angle of 60° with the horizontal ground. Assuming no slack, find the height of the kite above the ground. (√3 = 1.732)$q$, ARRAY[$q$30 m$q$,$q$60 m$q$,$q$51.96 m$q$,$q$34.64 m$q$], 3, $q$height = 60·sin60° = 60×(√3/2) = 51.96 m.$q$);
select public._seed_arith_q($q$Heights and Distances$q$, $q$easy$q$, $q$The angle of elevation of the top of a flagpole from a point 15 m away on level ground is 45°. Find the height of the flagpole.$q$, ARRAY[$q$10.6 m$q$,$q$15 m$q$,$q$21.2 m$q$,$q$7.5 m$q$], 2, $q$h = 15·tan45° = 15 m.$q$);
select public._seed_arith_q($q$Heights and Distances$q$, $q$medium$q$, $q$From the top of a 75 m high lighthouse, the angles of depression of two ships on the same side are 45° and 30°. Find the distance between the ships. (√3 = 1.732)$q$, ARRAY[$q$54.9 m$q$,$q$75 m$q$,$q$129.9 m$q$,$q$36.6 m$q$], 1, $q$d(45°)=75; d(30°)=75√3=129.9; distance=129.9−75=54.9 m.$q$);
select public._seed_arith_q($q$Heights and Distances$q$, $q$medium$q$, $q$The angle of elevation of the top of a tower from a point is 45°. On moving 30 m away from the tower, it becomes 30°. Find the height of the tower. (√3 = 1.732)$q$, ARRAY[$q$40.98 m$q$,$q$30 m$q$,$q$51.96 m$q$,$q$20 m$q$], 1, $q$h√3−h=30 ⇒ h=30/(√3−1)=15(√3+1)=40.98 m.$q$);
select public._seed_arith_q($q$Heights and Distances$q$, $q$medium$q$, $q$Two poles of equal height stand on either side of a road 120 m wide. From a point between them, the angles of elevation of their tops are 60° and 30°. Find the height of the poles. (√3 = 1.732)$q$, ARRAY[$q$51.96 m$q$,$q$60 m$q$,$q$34.64 m$q$,$q$30 m$q$], 1, $q$a+b=4h/√3=120 ⇒ h=30√3=51.96 m.$q$);
select public._seed_arith_q($q$Heights and Distances$q$, $q$medium$q$, $q$From the top of a building 40 m high, the angle of elevation of the top of a tower is 45° and the angle of depression of its foot is 30°. Find the height of the tower. (√3 = 1.732)$q$, ARRAY[$q$109.28 m$q$,$q$69.28 m$q$,$q$80 m$q$,$q$40 m$q$], 1, $q$Depression 30°: horizontal x=40√3=69.28; elevation 45°: extra=x·tan45°=69.28; tower=40+69.28=109.28 m.$q$);
select public._seed_arith_q($q$Heights and Distances$q$, $q$medium$q$, $q$A man observes the top of a tower at an elevation of 30°. On walking 50 m towards it, the elevation becomes 60°. Find the height of the tower. (√3 = 1.732)$q$, ARRAY[$q$43.3 m$q$,$q$50 m$q$,$q$25 m$q$,$q$86.6 m$q$], 1, $q$50=2h/√3 ⇒ h=25√3=43.3 m.$q$);
select public._seed_arith_q($q$Heights and Distances$q$, $q$medium$q$, $q$The length of the shadow of a vertical pole is equal to the height of the pole. What is the sun's angle of elevation at that moment?$q$, ARRAY[$q$30°$q$,$q$45°$q$,$q$60°$q$,$q$75°$q$], 2, $q$tanθ = height/shadow = 1 ⇒ θ = 45°.$q$);
select public._seed_arith_q($q$Heights and Distances$q$, $q$medium$q$, $q$When the sun's altitude changes from 30° to 45°, the shadow of a vertical tower shortens. If the tower is 30 m high, by how much does the shadow shorten? (√3 = 1.732)$q$, ARRAY[$q$21.96 m$q$,$q$30 m$q$,$q$51.96 m$q$,$q$12.68 m$q$], 1, $q$Shadow at 30° = 30√3 = 51.96 m; at 45° = 30 m; difference = 21.96 m.$q$);
select public._seed_arith_q($q$Heights and Distances$q$, $q$medium$q$, $q$A pole 30 m high casts a shadow of length 30√3 m on the ground. Find the sun's angle of elevation.$q$, ARRAY[$q$45°$q$,$q$60°$q$,$q$30°$q$,$q$15°$q$], 3, $q$tanθ = 30/(30√3) = 1/√3 ⇒ θ = 30°.$q$);
select public._seed_arith_q($q$Heights and Distances$q$, $q$medium$q$, $q$The angle of elevation of the top of a tower from a point 24 m from its base is 60°. What would the angle of elevation be from a point whose distance from the base equals the tower's height? (√3 = 1.732)$q$, ARRAY[$q$30°$q$,$q$45°$q$,$q$60°$q$,$q$90°$q$], 2, $q$Height = 24√3 m. From a point at distance = height, tanθ = height/dist = 1 ⇒ θ = 45°.$q$);
select public._seed_arith_q($q$Heights and Distances$q$, $q$hard$q$, $q$As a man walks 40 m towards a vertical tower on level ground, the angle of elevation of its top changes from 30° to 60°. Find the height of the tower. (√3 = 1.732)$q$, ARRAY[$q$40 m$q$,$q$34.64 m$q$,$q$69.28 m$q$,$q$20 m$q$], 2, $q$40 = h√3 − h/√3 = 2h/√3 ⇒ h = 20√3 = 34.64 m.$q$);
select public._seed_arith_q($q$Heights and Distances$q$, $q$hard$q$, $q$The angle of elevation of the top of a tower from a point on the ground is 30°. On walking 20 m towards the tower, the angle becomes 45°. Find the height of the tower. (√3 = 1.732)$q$, ARRAY[$q$27.32 m$q$,$q$20 m$q$,$q$34.64 m$q$,$q$10 m$q$], 1, $q$h√3 − h = 20 ⇒ h = 20/0.732 = 10(√3+1) = 27.32 m.$q$);
select public._seed_arith_q($q$Heights and Distances$q$, $q$hard$q$, $q$A flagstaff stands on top of a tower. From a point 30 m from the base, the angle of elevation of the top of the tower (foot of the flagstaff) is 30° and that of the top of the flagstaff is 60°. Find the height of the flagstaff. (√3 = 1.732)$q$, ARRAY[$q$17.32 m$q$,$q$51.96 m$q$,$q$34.64 m$q$,$q$30 m$q$], 3, $q$Tower = 30·tan30° = 17.32 m; top = 30·tan60° = 51.96 m; flagstaff = 51.96 − 17.32 = 34.64 m.$q$);
select public._seed_arith_q($q$Heights and Distances$q$, $q$hard$q$, $q$A boy observes the top of a tower at 30° elevation. He walks 60 m directly towards the tower and the elevation becomes 60°. What is the distance of the boy from the tower's base at the final position? (√3 = 1.732)$q$, ARRAY[$q$30 m$q$,$q$51.96 m$q$,$q$103.92 m$q$,$q$17.32 m$q$], 1, $q$h = 30√3; final distance = h/tan60° = 30√3/√3 = 30 m.$q$);
select public._seed_arith_q($q$Heights and Distances$q$, $q$hard$q$, $q$A flagstaff stands on top of a tower. From a point on the ground, the angle of elevation of the top of the tower (base of the flagstaff) is 45° and that of the top of the flagstaff is 60°. If the flagstaff is 5 m tall, find the height of the tower. (√3 = 1.732)$q$, ARRAY[$q$5 m$q$,$q$6.83 m$q$,$q$8.66 m$q$,$q$10 m$q$], 2, $q$Tower = x·tan45° = x; top = x·tan60° = x√3 = x+5 ⇒ x(√3−1)=5 ⇒ x = 5/0.732 = 6.83 m.$q$);
select public._seed_arith_q($q$Heights and Distances$q$, $q$hard$q$, $q$An aeroplane flying horizontally is observed at an angle of elevation of 60°. After 15 seconds of horizontal flight at constant height it flew 120 m horizontally and the angle became 30°. Find the constant height of the plane. (√3 = 1.732)$q$, ARRAY[$q$120 m$q$,$q$60 m$q$,$q$103.92 m$q$,$q$69.28 m$q$], 3, $q$distance = h√3 − h/√3 = 2h/√3 = 120 ⇒ h = 60√3 = 103.92 m.$q$);
select public._seed_arith_q($q$Heights and Distances$q$, $q$hard$q$, $q$The angle of elevation of the top of a hill from a point is 30°. After moving 90 m towards the hill, it becomes 60°. Find the height of the hill. (√3 = 1.732)$q$, ARRAY[$q$45 m$q$,$q$77.94 m$q$,$q$90 m$q$,$q$51.96 m$q$], 2, $q$90 = 2h/√3 ⇒ h = 45√3 = 77.94 m.$q$);
select public._seed_arith_q($q$Heights and Distances$q$, $q$hard$q$, $q$A man on the ground observes a bird on a pole at 45° elevation. He walks 10 m away from the pole and the elevation becomes 30°. Find the height of the pole. (√3 = 1.732)$q$, ARRAY[$q$13.66 m$q$,$q$10 m$q$,$q$17.32 m$q$,$q$5 m$q$], 1, $q$h·√3 − h = 10 ⇒ h = 10/0.732 = 5(√3+1) = 13.66 m.$q$);
select public._seed_arith_q($q$Heights and Distances$q$, $q$hard$q$, $q$A car moving towards a tower observes its top at 30°, and after travelling for 12 minutes at uniform speed the elevation is 60°. How much more time will it take to reach the foot of the tower?$q$, ARRAY[$q$12 minutes$q$,$q$24 minutes$q$,$q$6 minutes$q$,$q$4 minutes$q$], 3, $q$A→B (30°→60°) = 2h/√3; remaining B→foot = h/√3 = half of A→B ⇒ 12/2 = 6 minutes.$q$);
select public._seed_arith_q($q$Heights and Distances$q$, $q$very_hard$q$, $q$Two towers of equal height stand on either side of a road 80 m wide. From a point on the road between them, the angles of elevation of their tops are 30° and 60°. Find the height of the towers. (√3 = 1.732)$q$, ARRAY[$q$40 m$q$,$q$34.64 m$q$,$q$20 m$q$,$q$60 m$q$], 2, $q$a=h√3, b=h/√3, a+b=80 ⇒ 4h/√3=80 ⇒ h=20√3=34.64 m.$q$);
select public._seed_arith_q($q$Heights and Distances$q$, $q$very_hard$q$, $q$A man stands between two poles of equal height that are 100 m apart. From his position the angles of elevation of the tops of the poles are 60° and 30°. Find the height of the poles. (√3 = 1.732)$q$, ARRAY[$q$50 m$q$,$q$25 m$q$,$q$43.3 m$q$,$q$86.6 m$q$], 3, $q$a=h/√3, b=h√3, a+b=4h/√3=100 ⇒ h=25√3=43.3 m.$q$);
select public._seed_arith_q($q$Heights and Distances$q$, $q$very_hard$q$, $q$From the top of a building 30 m high, the angle of depression of the foot of a lamp post is 30° and the angle of elevation of its top is 45°. Find the height of the lamp post. (√3 = 1.732)$q$, ARRAY[$q$30 m$q$,$q$51.96 m$q$,$q$81.96 m$q$,$q$60 m$q$], 3, $q$Horizontal dist = 30/tan30° = 51.96 m; extra height = 51.96·tan45° = 51.96 m; post = 30 + 51.96 = 81.96 m.$q$);
select public._seed_arith_q($q$Heights and Distances$q$, $q$very_hard$q$, $q$From the top of a vertical cliff 150 m high, the angle of depression of a boat is 30°. The boat sails directly towards the cliff and the angle of depression becomes 60°. Find the distance travelled by the boat. (√3 = 1.732)$q$, ARRAY[$q$150 m$q$,$q$259.8 m$q$,$q$173.2 m$q$,$q$86.6 m$q$], 3, $q$travelled = 150√3 − 150/√3 = 300/√3 = 173.2 m.$q$);
select public._seed_arith_q($q$Heights and Distances$q$, $q$very_hard$q$, $q$A 60 m tall tower and a shorter building stand on level ground. From the top of the building, the angle of elevation of the tower's top is 30° and the angle of depression of the tower's foot is 60°. Find the height of the building. (√3 = 1.732)$q$, ARRAY[$q$45 m$q$,$q$30 m$q$,$q$15 m$q$,$q$40 m$q$], 1, $q$Depression 60°: b=x√3. Elevation 30°: 60−b=x/√3=b/3 ⇒ 60=4b/3 ⇒ b=45 m.$q$);
select public._seed_arith_q($q$Heights and Distances$q$, $q$very_hard$q$, $q$Two men on opposite sides of a tower observe its top at angles of elevation 30° and 60°. If the tower is 30 m high and the men and tower are collinear, find the distance between the two men. (√3 = 1.732)$q$, ARRAY[$q$51.96 m$q$,$q$69.28 m$q$,$q$34.64 m$q$,$q$103.92 m$q$], 2, $q$d1 = 30/tan30° = 51.96; d2 = 30/tan60° = 17.32; total = 69.28 m.$q$);
select public._seed_arith_q($q$Heights and Distances$q$, $q$very_hard$q$, $q$The angle of elevation of the top of a tower from the foot of a building is 60°, and from the top of the building (20 m high) it is 30°. The building and tower are on the same horizontal line. Find the height of the tower. (√3 = 1.732)$q$, ARRAY[$q$30 m$q$,$q$20 m$q$,$q$40 m$q$,$q$10 m$q$], 1, $q$From foot: H=x√3. From top: H−20=x/√3=H/3 ⇒ 20=2H/3 ⇒ H=30 m.$q$);
select public._seed_arith_q($q$Heights and Distances$q$, $q$very_hard$q$, $q$A tree stands on the bank of a river. From a point on the opposite bank the angle of elevation of the top of the tree is 60°, and from a point 40 m further back (in line, same bank) it is 30°. Find the width of the river (distance from the first point to the tree base). (√3 = 1.732)$q$, ARRAY[$q$40 m$q$,$q$34.64 m$q$,$q$20 m$q$,$q$69.28 m$q$], 3, $q$far−near=40, far=h√3, near=h/√3 ⇒ 2h/√3=40 ⇒ h=20√3; width=near=h/√3=20 m.$q$);
select public._seed_arith_q($q$Heights and Distances$q$, $q$very_hard$q$, $q$From the top of a 50 m high building, the angles of depression of the top and bottom of a shorter vertical tower on the same ground are 45° and 60° respectively. Find the height of the tower. (√3 = 1.732)$q$, ARRAY[$q$21.13 m$q$,$q$50 m$q$,$q$28.87 m$q$,$q$25 m$q$], 1, $q$Horizontal dist = 50/tan60° = 28.87 m; top of tower is 28.87·tan45° = 28.87 m below building top ⇒ tower = 50 − 28.87 = 21.13 m.$q$);

drop function public._seed_arith_q(text,text,text,text[],int,text);
